"""Fail-closed errors for Phase 06 activation governance."""

from __future__ import annotations

from enum import StrEnum


class ActivationErrorCode(StrEnum):
    """Stable machine-readable Phase 06 failure outcomes."""

    INVALID_CONTRACT = "INVALID_CONTRACT"
    INVALID_ACTIVATION_REQUEST = "INVALID_ACTIVATION_REQUEST"
    AUTHORITY_MISMATCH = "AUTHORITY_MISMATCH"
    TEST_FIXTURE_NOT_ALLOWED_AS_PRODUCTION_ACTIVATION_TARGET = (
        "TEST_FIXTURE_NOT_ALLOWED_AS_PRODUCTION_ACTIVATION_TARGET"
    )
    UNVERIFIED_ACTIVATION_TARGET = "UNVERIFIED_ACTIVATION_TARGET"
    STALE_ACTIVATION_TARGET = "STALE_ACTIVATION_TARGET"
    ILLEGAL_STATE_TRANSITION = "ILLEGAL_STATE_TRANSITION"
    TERMINAL_STATE_IMMUTABLE = "TERMINAL_STATE_IMMUTABLE"
    HUMAN_ACTIVATION_APPROVAL_REQUIRED = "HUMAN_ACTIVATION_APPROVAL_REQUIRED"
    ACTIVATION_CONCURRENCY_CONFLICT = "ACTIVATION_CONCURRENCY_CONFLICT"
    REPLAY_DETECTED = "REPLAY_DETECTED"
    TARGET_PUBLICATION_UNAVAILABLE = "TARGET_PUBLICATION_UNAVAILABLE"
    TARGET_PUBLICATION_TAMPERED = "TARGET_PUBLICATION_TAMPERED"
    TARGET_REPOSITORY_UNAVAILABLE = "TARGET_REPOSITORY_UNAVAILABLE"
    TARGET_REPOSITORY_HASH_MISMATCH = "TARGET_REPOSITORY_HASH_MISMATCH"
    UNKNOWN_ROLLBACK_TARGET = "UNKNOWN_ROLLBACK_TARGET"
    POINTER_TAMPERED = "POINTER_TAMPERED"
    REGISTRY_TAMPERED = "REGISTRY_TAMPERED"
    EVENT_CHAIN_TAMPERED = "EVENT_CHAIN_TAMPERED"
    PATH_REJECTED = "PATH_REJECTED"
    DIRECT_GRAPH_MUTATION_BLOCKED = "DIRECT_GRAPH_MUTATION_BLOCKED"
    SEMANTIC_AUTHORITY_ESCALATION_BLOCKED = "SEMANTIC_AUTHORITY_ESCALATION_BLOCKED"
    AUTO_ACTIVATION_BLOCKED = "AUTO_ACTIVATION_BLOCKED"
    ACTIVE_PUBLICATION_NOT_READY = "ACTIVE_PUBLICATION_NOT_READY"
    ACTIVE_REPOSITORY_MISMATCH = "ACTIVE_REPOSITORY_MISMATCH"
    INTEGRATION_CLEANUP_FAILED = "INTEGRATION_CLEANUP_FAILED"
    PHASE06_NOT_VERIFIED = "PHASE06_NOT_VERIFIED"


class ActivationError(ValueError):
    """A Phase 06 failure with a stable code and fail-closed status."""

    def __init__(
        self,
        code: ActivationErrorCode | str,
        detail: str | None = None,
    ) -> None:
        self.code = ActivationErrorCode(code)
        self.detail = detail or self.code.value
        super().__init__(self.detail)

    def to_dict(self) -> dict[str, str]:
        return {"code": self.code.value, "detail": self.detail, "status": "FAILED"}
