"""Fail-closed errors for the controlled Phase 05 boundary."""

from __future__ import annotations

from enum import StrEnum


class AmendmentErrorCode(StrEnum):
    INVALID_REQUEST = "INVALID_REQUEST"
    INVALID_CONTRACT = "INVALID_CONTRACT"
    AUTHORITY_MISMATCH = "AUTHORITY_MISMATCH"
    TEST_FIXTURE_NOT_ALLOWED_AS_PRODUCTION_AUTHORITY = (
        "TEST_FIXTURE_NOT_ALLOWED_AS_PRODUCTION_AUTHORITY"
    )
    UNAPPROVED_AMENDMENT = "UNAPPROVED_AMENDMENT"
    STALE_AMENDMENT_BASE = "STALE_AMENDMENT_BASE"
    REENTRY_TARGET_UNRESOLVED = "REENTRY_TARGET_UNRESOLVED"
    UNDECLARED_INPUT_CHANGE = "UNDECLARED_INPUT_CHANGE"
    AMENDMENT_SCOPE_VIOLATION = "AMENDMENT_SCOPE_VIOLATION"
    REENTRY_SEMANTIC_MISMATCH = "REENTRY_SEMANTIC_MISMATCH"
    AMENDMENT_NOT_REPRESENTED_BY_MODELING_PROPOSAL = (
        "AMENDMENT_NOT_REPRESENTED_BY_MODELING_PROPOSAL"
    )
    TBOX_AMENDMENT_NOT_EXECUTABLE_IN_PHASE05 = (
        "TBOX_AMENDMENT_NOT_EXECUTABLE_IN_PHASE05"
    )
    MANUAL_ONTOLOGY_MODELING_REQUIRED = "MANUAL_ONTOLOGY_MODELING_REQUIRED"
    NO_CHANGE_REENTRY_REQUIRED = "NO_REENTRY_REQUIRED"
    NO_PENDING_APPROVED_AMENDMENTS = "NO_PENDING_APPROVED_AMENDMENTS"
    REVIEW_REJECTED = "REVIEW_REJECTED"
    REVIEW_DEFERRED = "REVIEW_DEFERRED"
    AUTO_CONFIRM_BLOCKED = "AUTO_CONFIRM_BLOCKED"
    DIRECT_RDF_MUTATION_BLOCKED = "DIRECT_RDF_MUTATION_BLOCKED"
    GRAPHDB_INPLACE_MUTATION_BLOCKED = "GRAPHDB_INPLACE_MUTATION_BLOCKED"
    REPLAY_DETECTED = "REPLAY_DETECTED"
    PUBLICATION_IMMUTABILITY_VIOLATION = "PUBLICATION_IMMUTABILITY_VIOLATION"
    ARTIFACT_CLOSED_SET_MISMATCH = "ARTIFACT_CLOSED_SET_MISMATCH"
    DETERMINISM_FAILURE = "DETERMINISM_FAILURE"
    PHASE05_NOT_VERIFIED = "PHASE05_NOT_VERIFIED"


class AmendmentError(ValueError):
    """Stable error carrying a machine-readable Phase 05 outcome."""

    def __init__(self, code: AmendmentErrorCode | str, detail: str | None = None):
        self.code = AmendmentErrorCode(code)
        self.detail = detail or self.code.value
        super().__init__(self.detail)

    def to_dict(self) -> dict[str, str]:
        return {"code": self.code.value, "detail": self.detail, "status": "FAILED"}
