PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX mnp: <https://yangjunjie-lin.github.io/KG-MNP-Demo/ontology/terms#>
SELECT ?s ?p ?o WHERE { GRAPH <urn:kg-mnp:graph:abox:a952de54abc91ebfbeea0496ac11ccc9a29e988972500fe78e20ff4b6112dfdc> { ?s ?p ?o . FILTER(?p IN (<http://www.w3.org/2000/01/rdf-schema#domain>, <http://www.w3.org/2000/01/rdf-schema#range>, <http://www.w3.org/2000/01/rdf-schema#subClassOf>, <http://www.w3.org/2000/01/rdf-schema#subPropertyOf>, <http://www.w3.org/2002/07/owl#disjointWith>, <http://www.w3.org/2002/07/owl#equivalentClass>, <http://www.w3.org/2002/07/owl#equivalentProperty>) || (?p = <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> && ?o IN (<http://www.w3.org/2002/07/owl#Class>, <http://www.w3.org/2002/07/owl#DatatypeProperty>, <http://www.w3.org/2002/07/owl#ObjectProperty>, <http://www.w3.org/ns/shacl#NodeShape>, <http://www.w3.org/ns/shacl#PropertyShape>))) } } ORDER BY ?s ?p ?o
