import {test,expect} from '@playwright/test';
import fs from 'node:fs';
import crypto from 'node:crypto';

test('authorized fifth-stage handoff downloads the actual Worker snapshot',async({page},info)=>{
  test.skip(process.env.ZHIGOU_SAVED_EVIDENCE!=='1','Requires an explicitly generated synthetic service workspace.');
  test.setTimeout(240000);
  const credential=JSON.parse(fs.readFileSync(process.env.KG_MNP_BROWSER_CREDENTIAL!,'utf8'));
  await page.goto('/');
  await page.getByLabel('访问凭证').fill(credential.token);
  await page.getByRole('button',{name:'登录',exact:true}).click();
  const card=page.locator('a.project-card').first();
  await expect(card).toBeVisible({timeout:120000});
  const href=await card.getAttribute('href');
  if(!href)throw new Error('Synthetic project missing');
  const prefix=href.split('/').slice(0,3).join('/');
  await page.goto(prefix+'/modeling?stage=5');
  await expect(page.getByRole('button',{name:'本体交接包',exact:true})).toBeVisible({timeout:120000});
  let jobId=process.env.ZHIGOU_HANDOFF_EXPORT_JOB_ID;
  if(!jobId){
    await page.getByRole('button',{name:'本体交接包',exact:true}).click();
  await page.getByLabel('接收人', {exact:true}).fill('synthetic browser acceptance');
  await page.getByLabel('来源许可', {exact:true}).fill('PROJECT_SYNTHETIC_FIXTURE');
  await page.getByLabel('导出授权依据', {exact:true}).fill('Explicit synthetic browser engineering check');
  const acceptedPromise=page.waitForResponse(r=>r.url().endsWith('/operations/modeling.handoff.export')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'确认授权并生成交接包'}).click();
  const accepted=await acceptedPromise;
  expect(accepted.status()).toBe(202);
    jobId=(await accepted.json()).job_id;
  }
  const link=page.locator(`a[href$="/handoffs/${jobId}/archive"]`);
  await expect(link).toBeVisible({timeout:120000});
  const downloadPromise=page.waitForEvent('download');
  await link.click();
  const download=await downloadPromise;
  const output=info.outputPath('synthetic-ontology-handoff.zip');
  await download.saveAs(output);
  const job=await (await page.request.get(`/api/v1/jobs/${jobId}`,{timeout:120000})).json();
  expect(job.status).toBe('SUCCEEDED');
  const raw=fs.readFileSync(output);
  expect(raw.length).toBe(job.result.size_bytes);
  expect(crypto.createHash('sha256').update(raw).digest('hex')).toBe(job.result.sha256);
  expect(job.result.receiver_status).toBe('NOT_CONTACTED');
  await page.getByText('01–17 交付清单',{exact:true}).click();
  for(const label of ['01–08 上游输入','09–14 本体成果','15–17 演进数据'])await expect(page.getByText(label,{exact:true})).toBeVisible();
  await page.getByText('17 空批次或仅评价批次',{exact:true}).click();
  await page.getByLabel('演进批次编号',{exact:true}).fill('browser-empty-'+Date.now());
  const batchResponse=page.waitForResponse(r=>r.url().endsWith('/operations/modeling.evolution.export')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'生成所选演进批次',exact:true}).click();
  const batchAccepted=await batchResponse;expect(batchAccepted.status()).toBe(202);
  const batchId=(await batchAccepted.json()).job_id;
  const batchLink=page.locator(`a[href$="/handoffs/${batchId}/archive"]`);
  await expect(batchLink).toBeVisible({timeout:120000});
  const batchDownloadPromise=page.waitForEvent('download');await batchLink.click();
  const batchDownload=await batchDownloadPromise;
  const batchPath=info.outputPath('synthetic-empty-batch.zip');await batchDownload.saveAs(batchPath);
  const batchRaw=fs.readFileSync(batchPath);
  const batchApi=await page.request.get(`/api/v1${prefix}/handoffs/${batchId}/archive`);
  expect(batchApi.status()).toBe(200);expect(await batchApi.body()).toEqual(batchRaw);
  const batchJob=await (await page.request.get(`/api/v1/jobs/${batchId}`)).json();
  expect(batchJob.result.sha256).toBe(crypto.createHash('sha256').update(batchRaw).digest('hex'));
  expect(batchJob.result.receiver_status).toBe('NOT_CONTACTED');
  await page.screenshot({path:info.outputPath('handoff-stage-five.png'),fullPage:true});
});
