import {useState} from 'react';
import {DataTable, Field, Panel} from './components';
import {object, rows, str, type Document} from './api';

type LiteralRule = {field:string; predicate_iri:string; datatype:string};
type ReferenceRule = {field:string; predicate_iri:string; target_space:string};
type Alias = {value:string; canonical:string; rationale:string};
type Span = {field:string; item_id:string; start:number; end:number; quote:string};
type Rule = {record_id:string; class_iri:string; identity_space:string; id_field:string; literals:LiteralRule[]; references:ReferenceRule[]; identity_aliases:Alias[];
 source_id?:string; locator?:Document; template?:string; fields?:Span[]};
const initial = (id:string):Rule => ({record_id:id,class_iri:'',identity_space:'entities',id_field:'id',literals:[],references:[],identity_aliases:[]});

function PropertySelect({label,kind,value,elements,change}:{label:string;kind:string;value:string;elements:Document[];change:(v:string)=>void}) {
 return <Field label={label}><select required value={value} onChange={e=>change(e.target.value)}><option value="">请选择锁定基线元素</option>{elements.filter(e=>e.element_kind===kind).map(e=><option key={str(e.element_id)} value={str(e.iri)}>{str(e.iri)}</option>)}</select></Field>;
}

function RecordFields({rule,elements,change}:{rule:Rule;elements:Document[];change:(r:Rule)=>void}) {
 return <><div className="form-grid"><Field label="规则标识"><input required pattern="[a-z][a-z0-9-]{0,50}" value={rule.record_id} onChange={e=>change({...rule,record_id:e.target.value})}/></Field><PropertySelect label="对象类型" kind="CLASS" value={rule.class_iri} elements={elements} change={v=>change({...rule,class_iri:v})}/><Field label="共享身份空间"><input required pattern="[a-z][a-z0-9-]{0,50}" value={rule.identity_space} onChange={e=>change({...rule,identity_space:e.target.value})}/></Field><Field label="主键字段或文本槽名"><input required value={rule.id_field} onChange={e=>change({...rule,id_field:e.target.value})}/></Field></div>
 {rule.literals.map((field,index)=><div className="record" key={index}><div className="form-grid"><Field label={`数据字段 ${index+1}`}><input required value={field.field} onChange={e=>change({...rule,literals:rule.literals.map((f,i)=>i===index?{...f,field:e.target.value}:f)})}/></Field><PropertySelect label={`数据属性 ${index+1}`} kind="DATA_PROPERTY" value={field.predicate_iri} elements={elements} change={v=>change({...rule,literals:rule.literals.map((f,i)=>i===index?{...f,predicate_iri:v}:f)})}/><Field label={`数据类型 ${index+1}`}><select value={field.datatype} onChange={e=>change({...rule,literals:rule.literals.map((f,i)=>i===index?{...f,datatype:e.target.value}:f)})}>{['string','integer','decimal','boolean','date','dateTime'].map(v=><option key={v}>{v}</option>)}</select></Field></div><button type="button" onClick={()=>change({...rule,literals:rule.literals.filter((_,i)=>i!==index)})}>移除数据字段 {index+1}</button></div>)}
 <button type="button" onClick={()=>change({...rule,literals:[...rule.literals,{field:'',predicate_iri:'',datatype:'string'}]})}>添加数据属性</button>
 {rule.references.map((field,index)=><div className="record" key={index}><div className="form-grid"><Field label={`关联字段 ${index+1}`}><input required value={field.field} onChange={e=>change({...rule,references:rule.references.map((f,i)=>i===index?{...f,field:e.target.value}:f)})}/></Field><PropertySelect label={`对象属性 ${index+1}`} kind="OBJECT_PROPERTY" value={field.predicate_iri} elements={elements} change={v=>change({...rule,references:rule.references.map((f,i)=>i===index?{...f,predicate_iri:v}:f)})}/><Field label={`目标身份空间 ${index+1}`}><input required value={field.target_space} onChange={e=>change({...rule,references:rule.references.map((f,i)=>i===index?{...f,target_space:e.target.value}:f)})}/></Field></div><button type="button" onClick={()=>change({...rule,references:rule.references.filter((_,i)=>i!==index)})}>移除关联 {index+1}</button></div>)}
 <button type="button" onClick={()=>change({...rule,references:[...rule.references,{field:'',predicate_iri:'',target_space:''}]})}>添加跨来源关联</button>
 {rule.identity_aliases.map((alias,index)=><div className="record" key={index}><div className="form-grid">{[['value','原始主键'],['canonical','统一主键'],['rationale','身份合并依据']].map(([key,label])=><Field key={key} label={`${label} ${index+1}`}><input required value={alias[key as keyof Alias]} onChange={e=>change({...rule,identity_aliases:rule.identity_aliases.map((a,i)=>i===index?{...a,[key]:e.target.value}:a)})}/></Field>)}</div><button type="button" onClick={()=>change({...rule,identity_aliases:rule.identity_aliases.filter((_,i)=>i!==index)})}>移除身份别名 {index+1}</button></div>)}
 <button type="button" onClick={()=>change({...rule,identity_aliases:[...rule.identity_aliases,{value:'',canonical:'',rationale:''}]})}>声明身份别名</button></>;
}

function SpanPicker({items,append}:{items:Document[];append:(span:Span)=>void}) {
 const [selected,setSelected]=useState(''),[field,setField]=useState(''),[span,setSpan]=useState<Span|null>(null);
 const text=str(items.find(i=>i.item_id===selected)?.text);
 return <><Field label="标注原文条目"><select value={selected} onChange={e=>{setSelected(e.target.value);setSpan(null);}}><option value="">请选择</option>{items.map(i=><option key={str(i.item_id)} value={str(i.item_id)}>{str(i.text).slice(0,100)}</option>)}</select></Field><Field label="原文（选中要绑定的文字）"><textarea readOnly value={text} onSelect={e=>{const target=e.currentTarget;setSpan({field,item_id:selected,start:Array.from(text.slice(0,target.selectionStart)).length,end:Array.from(text.slice(0,target.selectionEnd)).length,quote:text.slice(target.selectionStart,target.selectionEnd)});}}/></Field><Field label="标注字段名"><input value={field} onChange={e=>setField(e.target.value)}/></Field><p>已选原文：{span?.quote||'未选择'}</p><button type="button" disabled={!span?.quote||!field.trim()} onClick={()=>{if(span){append({...span,field});setSpan(null);setField('');}}}>添加此原文片段</button></>;
}

export function MixedMappingForm({prepared,sources,busy,submit}:{prepared:Document;sources:Document[];busy:boolean;submit:(path:string,body:unknown)=>Promise<void>}) {
 const inventory=object(prepared.input_inventory),elements=rows(object(prepared.baseline).elements),physical=rows(inventory.tables),textItems=rows(inventory.text_items);
 const [tables,setTables]=useState<Record<number,Rule>>({}),[templates,setTemplates]=useState<Rule[]>([]),[annotations,setAnnotations]=useState<Rule[]>([]);
 const [exclusions,setExclusions]=useState<{item_id:string;rationale:string}[]>([]),[error,setError]=useState('');
 const name=(id:string)=>str(sources.find(s=>s.source_id===id)?.original_name)||id;
 const textSources=[...new Set(textItems.flatMap(i=>i.source_ids as string[]))];
 const serialize=(r:Rule)=>({...r,literals:Object.fromEntries(r.literals.map(({field,...mapping})=>[field,mapping]))});
 const allRules=[...Object.values(tables),...templates,...annotations];
 return <Panel title="混合资料建模：表格、文本与统一身份"><p>相同身份空间和主键才生成同一个对象；不同主键不会因同名或行号相同而合并。目标类与属性复用锁定基线。模板按完整行／段落匹配，不是通用自然语言理解。</p>
 <form onSubmit={e=>{e.preventDefault();setError('');if(allRules.some(r=>new Set(r.literals.map(f=>f.field)).size!==r.literals.length)){setError('同一规则中不能重复声明数据字段');return;}submit('/modeling/proposals',{bundle_id:object(prepared.bundle).modeling_input_bundle_id,providers:['manual-candidate-provider'],record_mapping:{profile:'evidence-record-mapping-v2',tables:Object.values(tables).map(serialize),text_templates:templates.map(serialize),text_records:annotations.map(serialize),exclusions}});}}>
 {physical.map((table,index)=><details className="record" key={index}><summary>{name(str(table.source_id))} · {str(object(table.locator).sheet)|| (object(table.locator).table_index!==null?`Word 表 ${Number(object(table.locator).table_index)+1}`:'分隔表格')}</summary><p>首行字段：{rows(table.headers).map(h=>str(h.name)).join('、')}</p><Field label={`纳入表格 ${index+1}`}><input type="checkbox" checked={!!tables[index]} onChange={e=>setTables(current=>{const updated={...current};if(e.target.checked)updated[index]={...initial(`table-${index+1}`),source_id:str(table.source_id),locator:object(table.locator)};else delete updated[index];return updated;})}/></Field>{tables[index]&&<RecordFields rule={tables[index]} elements={elements} change={r=>setTables({...tables,[index]:r})}/>}</details>)}
 <h3>文本模板</h3><p>例如：<code>{'实体 {id} 的标签为 {label}。'}</code>。槽名使用英文字母、数字或下划线；槽之间必须有固定文字。</p>
 {templates.map((rule,index)=><fieldset key={index}><legend>文本模板 {index+1}</legend><Field label={`模板资料 ${index+1}`}><select required value={rule.source_id} onChange={e=>setTemplates(templates.map((r,i)=>i===index?{...r,source_id:e.target.value}:r))}><option value="">请选择</option>{textSources.map(id=><option key={id} value={id}>{name(id)}</option>)}</select></Field><Field label={`匹配模板 ${index+1}`}><input required value={rule.template} onChange={e=>setTemplates(templates.map((r,i)=>i===index?{...r,template:e.target.value}:r))}/></Field><RecordFields rule={rule} elements={elements} change={r=>setTemplates(templates.map((v,i)=>i===index?r:v))}/><button type="button" onClick={()=>setTemplates(templates.filter((_,i)=>i!==index))}>移除模板 {index+1}</button></fieldset>)}
 <button type="button" disabled={!textSources.length} onClick={()=>setTemplates([...templates,{...initial(`text-${templates.length+1}`),source_id:'',template:''}])}>添加文本模板</button>
 <h3>任意段落的原文标注</h3><p>模板无法识别时，选取主键及事实值的原文片段，指定字段和目标。标注代表待审判断，不自动证明文本语义。</p>
 {annotations.map((rule,index)=><fieldset key={index}><legend>原文记录 {index+1}</legend><RecordFields rule={rule} elements={elements} change={r=>setAnnotations(annotations.map((v,i)=>i===index?r:v))}/><SpanPicker items={textItems} append={span=>setAnnotations(annotations.map((r,i)=>i===index?{...r,fields:[...r.fields||[],span]}:r))}/>{rule.fields?.map((span,n)=><div className="record" key={n}><span>{span.field}：{span.quote}（{span.start}–{span.end}）</span><button type="button" onClick={()=>setAnnotations(annotations.map((r,i)=>i===index?{...r,fields:r.fields?.filter((_,j)=>j!==n)}:r))}>移除片段 {n+1}</button></div>)}<button type="button" onClick={()=>setAnnotations(annotations.filter((_,i)=>i!==index))}>移除原文记录 {index+1}</button></fieldset>)}
 <button type="button" disabled={!textItems.length} onClick={()=>setAnnotations([...annotations,{...initial(`annotation-${annotations.length+1}`),fields:[]}])}>添加原文记录</button>
 <h3>明确排除的输入条目</h3><p>未覆盖条目会阻止确认。只可排除不在建模范围内的内容，并说明理由；不能用排除掩盖冲突事实。</p>
 {exclusions.map((entry,index)=><div className="form-grid" key={index}><Field label={`排除条目 ${index+1}`}><select required value={entry.item_id} onChange={e=>setExclusions(exclusions.map((v,i)=>i===index?{...v,item_id:e.target.value}:v))}><option value="">请选择</option>{(inventory.data_item_ids as string[]||[]).map(id=><option key={id} value={id}>{str(textItems.find(t=>t.item_id===id)?.text)||id}</option>)}</select></Field><Field label={`排除理由 ${index+1}`}><input required value={entry.rationale} onChange={e=>setExclusions(exclusions.map((v,i)=>i===index?{...v,rationale:e.target.value}:v))}/></Field><button type="button" onClick={()=>setExclusions(exclusions.filter((_,i)=>i!==index))}>移除排除项 {index+1}</button></div>)}
 <button type="button" onClick={()=>setExclusions([...exclusions,{item_id:'',rationale:''}])}>添加范围排除</button>{error&&<p role="alert">{error}</p>}<button disabled={busy||!allRules.length}>生成混合资料候选</button></form></Panel>;
}

export function ExtractionReport({report}:{report:Document}) {
 const unmapped=report.unmapped_item_ids as string[]||[];
 return <Panel title="来源覆盖与身份核对"><p role="status">{unmapped.length?`尚有 ${unmapped.length} 条输入未映射，不能确认。请补充映射或有理由的范围排除后重新生成候选。`:'所选输入条目均已映射或明确排除；仍需逐项语义审核。条目覆盖不等于段落内每句话都已理解。'}</p><p>映射摘要：<code>{str(report.mapping_digest)}</code></p><DataTable data={rows(report.identities)} fields={[["iri","统一实体"],["occurrences","跨来源记录数"],["item_ids","来源条目"]]}/><DataTable data={rows(report.text_spans)} fields={[["field","文本字段"],["quote","原文值"],["start","起点"],["end","终点"],["item_id","原文条目"]]}/>{!!unmapped.length&&<DataTable data={unmapped.map(item_id=>({item_id}))} fields={[["item_id","尚未映射"]]}/>}</Panel>;
}
