import {useState} from 'react';
import {Field,Panel} from './components';
import {object,rows,str,type Document} from './api';

export function RecordMappingForm({prepared,sources,busy,submit}:{prepared:Document;sources:Document[];busy:boolean;submit:(path:string,body:unknown)=>Promise<void>}){
 const [fields,setFields]=useState([{source:'',target:''}]);
 const elements=rows(object(prepared.baseline).elements);
 return <Panel title="自定义记录映射候选"><p>只定义候选规则，不修改已发布语义。目标类和属性来自锁定基线，每项生成结果仍需人工审核。</p><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);submit('/modeling/proposals',{bundle_id:object(prepared.bundle).modeling_input_bundle_id,providers:['manual-candidate-provider'],record_mapping:{profile:'evidence-record-mapping-v1',tables:[{table_id:data.get('table'),source_name:data.get('source'),class_iri:data.get('class'),id_field:data.get('id'),literals:Object.fromEntries(fields.filter(f=>f.source&&f.target).map(f=>[f.source,f.target])),references:[]}]}});}}><div className="form-grid"><Field label="记录表标识"><input name="table" required pattern="[a-z][a-z0-9-]*"/></Field><Field label="映射资料文件"><select name="source" required defaultValue=""><option value="">请选择</option>{sources.map(s=><option key={str(s.source_id)}>{str(s.original_name)}</option>)}</select></Field><Field label="目标基线类"><select name="class" required defaultValue=""><option value="">请选择</option>{elements.filter(e=>e.element_kind==='CLASS').map(e=><option key={str(e.element_id)} value={str(e.iri)}>{str(e.iri)}</option>)}</select></Field><Field label="来源身份字段"><input name="id" required/></Field></div>{fields.map((field,index)=><div className="form-grid" key={index}><Field label={`来源字段 ${index+1}`}><input required value={field.source} onChange={e=>setFields(fields.map((f,i)=>i===index?{...f,source:e.target.value}:f))}/></Field><Field label={`目标数据属性 ${index+1}`}><select required value={field.target} onChange={e=>setFields(fields.map((f,i)=>i===index?{...f,target:e.target.value}:f))}><option value="">请选择</option>{elements.filter(e=>e.element_kind==='DATA_PROPERTY').map(e=><option key={str(e.element_id)} value={str(e.iri)}>{str(e.iri)}</option>)}</select></Field></div>)}<button type="button" onClick={()=>setFields([...fields,{source:'',target:''}])}>添加字段映射</button><button disabled={busy}>生成自定义映射候选</button></form></Panel>;
}
