import { useState } from 'react';
import { object, outputs, rows, str } from './api';
import { DataTable, Field, Id, Panel, SelectDocument, PackageDownload } from './components';
import { useWorkspace } from './shell';
import {ReleaseReview} from './release-review';
import {ObjectBrowser} from './object-browser';
export function Releases() {
  const {state,submit,busy,principal}=useWorkspace(); const [confirmed,setConfirmed]=useState('');
  const confirmedPackages=outputs(state,'review.finalize','confirmed_package'); const builds=state.results.filter(r=>r.operation==='compile.build');
  const plans=outputs(state,'compile.plan','plan'), candidates=state.results.filter(r=>r.operation==='release.candidate').map(r=>r.result), reviews=state.results.filter(r=>r.operation==='release.review').map(r=>r.result);
  const imported=new Set(state.results.filter(r=>r.operation==='registry.import').map(r=>str(r.result.package_id)));
  const questions=state.results.filter(r=>r.operation==='modeling.prepare').flatMap(r=>rows(object(r.result.questions).questions));
  return <><h1>验证与发布</h1><Panel title="编译计划与明确 Oracle"><SelectDocument label="确认包" items={confirmedPackages} idKey="package_id" value={confirmed} onChange={setConfirmed}/><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);submit('/compilations/plans',{confirmed_package_id:confirmed,package_name:f.get('name'),package_version:f.get('version'),ontology_iri:f.get('ontology'),version_iri:f.get('versionIri'),oracles:[{question_id:f.get('question'),query_asset_id:f.get('query'),min_rows:Number(f.get('rows')),required_bindings:String(f.get('bindings')).split(',').map(s=>s.trim())}]});}}><div className="form-grid"><Field label="本体包名称"><input name="name" required pattern="[a-z][a-z0-9-]*"/></Field><Field label="本体包版本"><input name="version" required placeholder="0.1.0"/></Field><Field label="Ontology IRI"><input name="ontology" required/></Field><Field label="Version IRI"><input name="versionIri" required/></Field><Field label="能力问题"><select name="question" required defaultValue=""><option value="">请选择</option>{questions.map(q=><option key={str(q.question_id)} value={str(q.question_id)}>{str(q.question_text)}</option>)}</select></Field><Field label="锁定领域包中的查询 Asset ID"><input name="query" required/></Field><Field label="最少结果行数（非空 Oracle）"><input name="rows" type="number" min="1" required defaultValue="1"/></Field><Field label="必须返回的变量（逗号分隔）"><input name="bindings" required/></Field></div><button disabled={busy||!confirmed}>生成编译计划</button></form>{plans.map(p=><div className="record" data-testid={'compilation-plan-'+str(p.plan_id)} key={str(p.plan_id)}><Id value={p.plan_id}/><button disabled={busy} onClick={()=>submit('/compilations/builds',{plan_id:p.plan_id})}>执行真实编译与验证</button></div>)}</Panel><Panel title="正式验证结果">{builds.length===0?<p className="empty">尚无成功编译。本体包仅在全部必需语义门通过后出现；失败原因见任务中心。</p>:builds.map(b=><div data-testid={'package-build-'+str(b.result.package_id)} key={b.job_id}><Id value={b.result.package_id}/><PackageDownload projectId={state.project.project_id} packageId={str(b.result.package_id)} allowed={principal.permissions.includes('*')||principal.permissions.includes('package:export')}/><DataTable data={Object.entries(object(b.result.reports)).map(([name,value])=>({name,status:object(value).status,required_passed:object(value).required_passed}))} fields={[["name","验证报告"],["status","执行状态"],["required_passed","必需检查通过"]]}/><button disabled={busy||imported.has(str(b.result.package_id))} onClick={()=>submit('/lifecycle/imports',{package_id:b.result.package_id})}>验证并导入本地 Registry</button><button disabled={busy} onClick={()=>submit('/lifecycle/release-candidates',{package_id:b.result.package_id})}>创建初始 Release Candidate</button></div>)}</Panel><ReleaseReview candidates={candidates} reviews={reviews}/><ObjectBrowser packages={builds.map(build=>build.result)} releases={outputs(state,'release.publish','release')}/></>;
}
