import { lazy, Suspense, useEffect, useRef, useState, type FormEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link, NavLink, Navigate, Outlet, Route, Routes, useNavigate, useOutletContext, useParams } from 'react-router-dom';
import { api, ApiError, clearIdentity, post, queryClient, setCsrf, type Pack, type Principal, type Project, type ProjectState } from './api';
import { Field, Id, Panel, Status, DataTable } from './components';
import { Sources } from './sources';
const Modeling = lazy(()=>import('./modeling').then(module=>({default:module.Modeling})));
import { Releases } from './releases';
import { Versions } from './versions';

export type WorkspaceContext = {state: ProjectState; principal: Principal; prefix: string; busy: boolean; submit: (path: string, body: unknown) => Promise<void>};
export function useWorkspace() { return useOutletContext<WorkspaceContext>(); }
function Login({onLogin}: {onLogin: () => void}) {
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const form = event.currentTarget; const credential = String(new FormData(form).get('credential'));
    try { const result = await api<{csrf_token: string}>('/session', {method: 'POST', headers: {Authorization: `Bearer ${credential}`}}); form.reset(); clearIdentity(); setCsrf(result.csrf_token); onLogin(); }
    catch (err) {form.reset(); setError(String(err));} finally {setBusy(false);} }
  return <main className="login"><div className="brand">KG-MNP <span>Ontology Toolchain</span></div><Panel title="登录本体工程工作台"><p>使用本地管理员签发的凭证。此页面不提供管理员注册。</p><form onSubmit={login}><Field label="访问凭证"><input name="credential" type="password" autoComplete="off" required /></Field><button disabled={busy}>登录</button></form>{error && <p role="alert" className="error">{error}</p>}<p className="muted">长期凭证不会保存到浏览器存储。后台任务由当前服务器授权控制。</p></Panel></main>;
}
export function App() {
  const session = useQuery({queryKey: ['session'], queryFn: ({signal}) => api<{principal: Principal; csrf_token: string}>('/session', {signal}), refetchInterval: 30000});
  useEffect(() => {if (session.data) setCsrf(session.data.csrf_token);}, [session.data]);
  if (session.isPending) return <main className="login" role="status">正在检查会话…</main>;
  if (!session.data || session.isError) return <Login onLogin={() => window.location.assign('/')} />;
  return <Routes><Route path="/" element={<Projects principal={session.data.principal} />} /><Route path="/projects/:projectId" element={<Workspace principal={session.data.principal} />}><Route index element={<Navigate to="overview" replace />} /><Route path="overview" element={<Overview />} /><Route path="sources" element={<Sources />} /><Route path="modeling" element={<Suspense fallback={<p role="status">正在加载建模视图…</p>}><Modeling /></Suspense>} /><Route path="releases" element={<Releases />} /><Route path="versions" element={<Versions />} /><Route path="jobs" element={<Jobs />} /></Route><Route path="*" element={<main className="login"><h1>页面不存在</h1><Link to="/">返回项目选择</Link></main>} /></Routes>;
}
async function logout() { try { await post('/session/logout', {}); } finally {clearIdentity(); window.location.assign('/');} }
function Projects({principal}: {principal: Principal}) {
  const navigate = useNavigate(); const [error, setError] = useState('');
  const projects = useQuery({queryKey: ['projects', principal.principal_id], queryFn: () => api<{projects: Project[]}>('/projects')});
  const packs = useQuery({queryKey: ['packs', principal.principal_id], queryFn: () => api<{domain_packs: Pack[]}>('/domain-packs')});
  async function create(event: FormEvent<HTMLFormElement>) {event.preventDefault(); const form = new FormData(event.currentTarget); const [domain_pack, domain_pack_version] = String(form.get('pack')).split('@'); setError(''); try { const project = await post<Project>('/projects', {name: form.get('name'), domain_pack, domain_pack_version}); navigate(`/projects/${encodeURIComponent(project.project_id)}/overview`); } catch(err) {setError(String(err));} }
  return <main className="projects"><header className="top"><div className="brand">KG-MNP <span>本体工程工作台</span></div><span>{principal.principal_id}</span><button onClick={logout}>退出</button></header><h1>选择项目</h1><p className="muted">项目绑定明确的领域包版本，资料、审核和本体包相互隔离。</p>{(projects.error || packs.error || error) && <p role="alert" className="error">{String(projects.error || packs.error || error)}</p>}<div className="project-grid"><Panel title="已有项目">{projects.isPending ? <p role="status">正在读取…</p> : !projects.data?.projects.length ? <p className="empty">暂无可访问项目</p> : projects.data.projects.map(p => <Link className="project-card" key={p.project_id} to={`/projects/${encodeURIComponent(p.project_id)}/overview`}><strong>{p.project_name}</strong><span>{p.domain_pack} · {p.domain_pack_version}</span><Status value={p.status} /></Link>)}</Panel><Panel title="创建项目"><form onSubmit={create}><Field label="项目名称"><input name="name" required maxLength={200} /></Field><Field label="领域包与版本"><select name="pack" required defaultValue=""><option value="">请选择领域包</option>{packs.data?.domain_packs.map(p => <option key={p.pack_id} value={`${p.pack_id}@${p.pack_version}`} disabled={p.availability !== 'AVAILABLE'}>{p.display_name || p.pack_id} · {p.pack_version} · {p.lifecycle}</option>)}</select></Field><button>创建项目</button></form></Panel></div></main>;
}
function Workspace({principal}: {principal: Principal}) {
  const {projectId = ''} = useParams(); const prefix = `/projects/${encodeURIComponent(projectId)}`; const [collapsed, collapse] = useState(false); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const keys = useRef(new Map<string,string>());
  const state = useQuery({queryKey: ['state', principal.principal_id, projectId], queryFn: ({signal}) => api<ProjectState>(`${prefix}/state`, {signal}), refetchInterval: 2000});
  useEffect(() => {setMessage(''); keys.current.clear(); return () => {queryClient.removeQueries({predicate:q=>q.queryKey.includes(projectId)});};}, [projectId, principal.principal_id]);
  useEffect(() => {if (state.error instanceof ApiError && state.error.status === 401) clearIdentity();}, [state.error]);
  async function submit(path: string, body: unknown) {const signature = path + JSON.stringify(body); const key = keys.current.get(signature) || crypto.randomUUID(); keys.current.set(signature,key); setBusy(true); setMessage(''); try {const result = await post<{job_id?: string}>(prefix + path, body,key); setMessage(result.job_id ? `任务已提交：${result.job_id}。请查看任务中心；关闭页面不会取消任务。` : '操作已完成'); await queryClient.invalidateQueries({queryKey: ['state']});} catch(err) {setMessage(String(err));} finally {setBusy(false);} }
  const navigation = [['overview','项目概览'],['sources','资料与证据'],['modeling','本体建模与审核'],['releases','验证与发布'],['versions','差异与环境'],['jobs','任务中心']];
  return <div className={`workspace ${collapsed ? 'collapsed' : ''}`}><aside><div className="brand">KG-MNP</div><button aria-expanded={!collapsed} onClick={() => collapse(!collapsed)}>{collapsed ? '展开导航' : '收起导航'}</button><nav aria-label="工作台导航">{navigation.map(([path,label]) => <NavLink key={path} to={`${prefix}/${path}`}>{label}</NavLink>)}</nav><Link to="/">切换项目</Link></aside><div className="workspace-main"><header className="top"><strong>{state.data?.project.project_name || '项目工作台'}</strong><span>{principal.principal_id} · {principal.principal_type}</span><button onClick={logout}>退出</button></header><main><p className="notice">开发中版本 · 尚未通过完整发行验收。环境回滚、完整跨领域验证和旧入口退役仍未完成。</p>{message && <p role="status" className="notice">{message}</p>}{state.error ? <p role="alert" className="error">读取失败：{String(state.error)}<button onClick={() => state.refetch()}>重试读取</button></p> : state.data ? <Outlet context={{state: state.data, principal, prefix, busy, submit} satisfies WorkspaceContext} /> : <p role="status">正在读取项目状态…</p>}</main></div></div>;
}
function Overview() {const {state} = useWorkspace(); return <><h1>项目概览</h1><Panel title="项目与权威版本"><dl><dt>领域包</dt><dd>{state.project.domain_pack} · {state.project.domain_pack_version}</dd><dt>Workspace 状态</dt><dd><Status value={state.project.status}/></dd><dt>项目修订</dt><dd>{state.project.authority_revision}</dd><dt>项目 ID</dt><dd><Id value={state.project.project_id}/></dd></dl></Panel><Panel title="工作流程"><ol className="workflow"><li>上传资料并运行解析计划</li><li>核验证据、定义范围与能力问题</li><li>生成候选并逐项人工审核</li><li>确认、编译与实际语义验证</li><li>导入注册表、审核并发布初始版本</li></ol></Panel><Panel title="最新任务"><DataTable data={state.jobs.slice(0,10)} fields={[["operation_id","操作"],["status","状态"],["job_id","任务 ID"]]}/></Panel></>; }
function Jobs() {const {state, submit, busy} = useWorkspace(); return <><h1>任务中心</h1><p>取消运行中的任务表示“请求取消”，不等于工件已撤销。已经提交的结果保持有效。</p>{state.jobs.map(job => <Panel key={job.job_id} title={job.operation_id}><Id value={job.job_id}/><p><Status value={job.status}/>{job.error && <span role="alert" className="error">{job.error.code}</span>}</p><button disabled={busy || !['QUEUED','RUNNING'].includes(job.status)} onClick={async () => {await post(`/jobs/${job.job_id}/cancel`,{}); await queryClient.invalidateQueries({queryKey:['state']});}}>请求取消</button></Panel>)}</>; }
