import { useState, type FormEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api, outputs, rows, str, type Document, queryClient } from './api';
import { DataTable, Field, Panel, SelectDocument } from './components';
import { useWorkspace } from './shell';
export function Sources() {
  const {state, prefix, submit, busy} = useWorkspace(); const [run, setRun] = useState(''); const [uploading, setUploading] = useState(false); const [error, setError] = useState('');
  const registered = outputs(state,'source.register','source'), batches = [...outputs(state,'source.register','batch'),...outputs(state,'source.batch','batch')], plans = outputs(state,'ingestion.plan','plan'), runs = outputs(state,'ingestion.run','run');
  const evidence = useQuery({queryKey:['evidence',state.project.project_id,run], queryFn: ({signal}) => api<{evidence: Document[]; transformations: Document[]}>(`${prefix}/evidence?run_id=${encodeURIComponent(run)}`, {signal}), enabled: !!run});
  async function upload(event: FormEvent<HTMLFormElement>) {event.preventDefault(); const form = event.currentTarget; const file = new FormData(form).get('file') as File; setUploading(true); setError(''); try {await api(`${prefix}/sources`, {method:'POST',headers:{'Content-Type':file.type || 'application/octet-stream','X-Filename':encodeURIComponent(file.name),'Idempotency-Key':crypto.randomUUID()},body:file}); form.reset(); await queryClient.invalidateQueries({queryKey:['state']});} catch(err) {setError(String(err));} finally {setUploading(false);} }
  return <><h1>数据接入与规则化</h1><p className="muted">文件与 API 输入保留类型化来源位置，规则化结果可独立评测并交给本体建模。</p><button disabled={busy||registered.length>0} onClick={()=>submit('/toolchain/source.sample.load',{})}>加载当前领域包的合成批次（仅空项目）</button><Panel title="上传资料"><form onSubmit={upload}><Field label="资料文件"><input name="file" type="file" required /></Field><button disabled={uploading}>{uploading ? '正在接收…' : '上传并登记 Source'}</button></form><p className="muted">文件是待解析资料，不会安装插件或执行代码。解析失败不会自动切换模拟数据。</p>{error && <p role="alert" className="error">{error}</p>}</Panel><Panel title="已登记来源"><DataTable data={registered} fields={[["original_name","资料名称"],["detected_media_type","检测格式"],["size_bytes","字节数"],["source_id","Source ID"]]}/></Panel><Panel title="组合资料批次"><form onSubmit={e=>{e.preventDefault();submit('/source-batches',{source_ids:new FormData(e.currentTarget).getAll('source')});}}>{registered.map(s=><Field key={str(s.source_id)} label={str(s.original_name)}><input type="checkbox" name="source" value={str(s.source_id)}/></Field>)}<button disabled={busy}>创建选中来源的批次</button></form></Panel><Panel title="解析计划与任务"><form onSubmit={e => {e.preventDefault(); submit('/ingestion/plans',{batch_id:new FormData(e.currentTarget).get('batch')});}}><Field label="资料批次"><select name="batch" required defaultValue=""><option value="">请选择</option>{batches.map(b => <option key={str(b.batch_id)}>{str(b.batch_id)}</option>)}</select></Field><button disabled={busy}>生成解析计划</button></form>{plans.map(p => <div className="record" key={str(p.plan_id)}><code>{str(p.plan_id)}</code><span>{str(p.status)}</span>{rows(p.issues).map((i,n)=><p key={n}>{str(i.code)}：{str(i.message)}</p>)}<button disabled={busy || p.status !== 'READY'} onClick={() => submit('/ingestion/runs',{plan_id:p.plan_id})}>运行解析</button></div>)}</Panel><Panel title="证据定位与转换记录"><SelectDocument label="解析运行" items={runs} idKey="run_id" value={run} onChange={setRun}/>{evidence.isError ? <p role="alert" className="error">{String(evidence.error)}</p> : evidence.isFetching ? <p role="status">正在核验证据链…</p> : evidence.data && <><DataTable data={evidence.data.evidence} fields={[["observed_value","原始观察值"],["locator","来源定位"],["source_id","Source"],["evidence_id","Evidence ID"]]}/><DataTable data={evidence.data.transformations} fields={[["transformation_type","转换"],["transformation_id","转换 ID"]]}/>{registered.map(s => <p key={str(s.source_id)}><a href={`/api/v1${prefix}/sources/${encodeURIComponent(str(s.source_id))}/content`}>下载原始资料：{str(s.original_name)}</a></p>)}</>}</Panel></>;
}
