import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {api, object, outputs, rows, str, type Document} from './api';
import {DataTable, Field, Panel, SelectDocument, Status} from './components';
import {useWorkspace} from './shell';
import {ArtifactViewer} from './modeling-components';
import {Versions} from './versions';
import {Integrations} from './integrations';

export function ModuleEvaluation({module}:{module:string}){
  const {state,submit,busy}=useWorkspace();const [artifact,setArtifact]=useState('');
  const results=state.results.filter(r=>r.operation==='module.evaluate'&&object(r.result.report).module===module);
  return <details className="module-evaluation"><summary>独立效果测试</summary><p>选择真实运行记录，执行模块契约与来源检查。工程检查不代替标注数据集上的研究指标。</p><Field label="受测任务 ID"><select value={artifact} onChange={e=>setArtifact(e.target.value)}><option value="">请选择真实上游运行</option>{state.results.map(r=><option key={r.job_id} value={r.job_id}>{r.operation} · {r.job_id}</option>)}</select></Field><button disabled={busy||!artifact} onClick={()=>submit('/toolchain/module.evaluate',{module,job_id:artifact})}>运行独立效果测试</button>{results.map(r=><ArtifactViewer key={r.job_id} title="模块评测报告" value={r.result.report}/>)}</details>;
}
export function TaskExecution(){
  const {state,prefix,submit,busy}=useWorkspace();const [packageId,setPackage]=useState('');
  const plans=outputs(state,'task.plan','plan'),executions=outputs(state,'task.execute','execution');
  const business=useQuery({queryKey:['business',prefix,state.project.authority_revision],queryFn:()=>api<{payload:Document}>(`/operations/business.inspect`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_id:state.project.project_id})})});
  return <><h1>任务规划与业务执行</h1><p className="muted">固定本体版本 → 受控动作计划 → 持久化业务状态。当前执行器只在本地测试工作区运行；任务说明用于审计，具体动作由锁定领域策略决定，不声称理解任意自然语言任务。</p><div className="compare-grid"><Panel title="输入 · 业务目标与本体"><SelectDocument label="固定本体包" items={state.results.filter(r=>r.operation==='compile.build').map(r=>r.result)} idKey="package_id" value={packageId} onChange={setPackage}/><form onSubmit={e=>{e.preventDefault();submit('/toolchain/task.plan',{package_id:packageId,goal:new FormData(e.currentTarget).get('goal')});}}><Field label="业务任务说明（固定领域策略）"><textarea name="goal" required/></Field><button disabled={busy||!packageId}>通过本体服务规划</button></form></Panel><Panel title="输出 · 计划与实际动作">{plans.map(p=><div className="record" key={str(p.plan_id)}><p>{str(p.goal)}</p><DataTable data={rows(p.items)} fields={[["state","来源状态"],["decision","计划动作"],["priority","优先级"]]}/><button disabled={busy} onClick={()=>submit('/toolchain/task.execute',{plan_id:p.plan_id})}>执行已登记动作并重读结果</button><details><summary>固定版本与动作依据</summary><ArtifactViewer value={p}/></details></div>)}</Panel></div><Panel title="当前持久化工单">{business.error&&<p role="alert">{String(business.error)}</p>}<p role="status">{business.isPending?'正在读取持久化工单…':business.isFetching?'正在刷新工单状态…':`已读取 ${Object.keys(object(business.data?.payload.orders)).length} 条工单`}</p><DataTable data={Object.values(object(business.data?.payload.orders)).map(object)} fields={[["object","业务对象"],["inspection","来源巡查"],["status","业务状态"],["priority","优先级"]]}/>{executions.map(e=><div key={str(e.execution_id)}><Status value={e.status}/><p>待核实 {rows(e.pending_verification).length} 项，明确无需动作 {rows(e.skipped).length} 项。</p><details><summary>执行收据与来源</summary><ArtifactViewer value={e}/></details></div>)}</Panel><ModuleEvaluation module="framework"/></>;
}
export function FeedbackEvolution(){
  const {state,submit,busy}=useWorkspace();const [execution,setExecution]=useState('');
  const candidates=new Map<string,Document>();for(const r of state.results){const c=object(r.result.candidate);if(r.operation.startsWith('evolution.')&&c.candidate_id)candidates.set(str(c.candidate_id),c);}
  return <><h1>反馈评估与演进</h1><p className="muted">回归验证通过且人工审核完成后，执行配置才作用于下一轮新计划。既有工单不被回溯改写。</p><div className="compare-grid"><Panel title="输入 · 实际执行记录与反馈"><SelectDocument label="执行记录" items={outputs(state,'task.execute','execution')} idKey="execution_id" value={execution} onChange={setExecution}/><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);submit('/toolchain/evolution.propose',{execution_id:execution,feedback:f.get('feedback'),priority:f.get('priority'),version:f.get('version')});}}><Field label="人工反馈与问题依据"><textarea name="feedback" required/></Field><Field label="候选工单优先级"><select name="priority"><option value="normal">常规</option><option value="high">高</option></select></Field><Field label="候选配置版本"><input name="version" required placeholder="1.1.0"/></Field><button disabled={busy||!execution}>提出配置变更候选</button></form></Panel><Panel title="输出 · 回归、审核与更新">{[...candidates.values()].map(c=><section key={str(c.candidate_id)} className="record"><Status value={c.status}/><p>{str(c.feedback)}</p><button disabled={busy} onClick={()=>submit('/toolchain/evolution.evaluate',{candidate_id:c.candidate_id})}>运行隔离回归</button><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);submit('/toolchain/evolution.review',{candidate_id:c.candidate_id,rationale:f.get('rationale'),decision:f.get('decision')});}}><Field label="变更审核理由"><textarea name="rationale" required/></Field><Field label="变更审核决定"><select name="decision"><option value="APPROVE">批准</option><option value="REJECT">拒绝</option></select></Field><button disabled={busy||c.status!=='VALIDATED'}>以当前服务器身份审核</button></form><button disabled={busy||c.status!=='APPROVED'} onClick={()=>submit('/toolchain/evolution.activate',{candidate_id:c.candidate_id})}>启用已审核配置</button><details><summary>前后结果与受测依据</summary><ArtifactViewer value={c}/></details></section>)}</Panel></div><ModuleEvaluation module="evolution"/><details><summary>本体与规则版本变更、环境回滚</summary><Versions/></details></>;
}
export function ServiceDetails(){return <details><summary>版本选择、回滚与外部集成状态</summary><Versions/><Integrations/></details>;}
