PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?graph ?term ?termType ?label ?definition ?domain ?range ?subPropertyOf
WHERE {
  VALUES ?graph { @@GRAPH_graph@@ }
  GRAPH ?graph {
    VALUES ?termType { owl:ObjectProperty owl:DatatypeProperty owl:AnnotationProperty }
    ?term a ?termType .
    OPTIONAL { ?term rdfs:label ?label . }
    OPTIONAL { ?term rdfs:comment ?definition . }
    OPTIONAL { ?term rdfs:domain ?domain . }
    OPTIONAL { ?term rdfs:range ?range . }
    OPTIONAL { ?term rdfs:subPropertyOf ?subPropertyOf . }
  }
}
ORDER BY ?term ?termType ?label ?domain ?range ?subPropertyOf
LIMIT @@LIMIT@@
OFFSET @@OFFSET@@
