"""Independent stage negatives, native ancestry, and tamper-resistant receipts."""
from __future__ import annotations

import json
import os
from copy import deepcopy
from pathlib import Path

import pytest

from tests.upgrade.test_full_chain import build_case
from tests.upgrade.test_handoff_delivery import request_for
from zhigou_toolchain.modeling.delivery.bindings import (
    associate_trace,
    dependency_parts,
    validate_trace_context,
    verify_ancestor,
)
from zhigou_toolchain.modeling.delivery.cover import compose, verify_cover
from zhigou_toolchain.modeling.delivery.exchange_io import digest, json_bytes
from zhigou_toolchain.modeling.delivery.handoff import handoff_files, verify_handoff
from zhigou_toolchain.modeling.delivery.negative import execute_negative_plan
from zhigou_toolchain.modeling.delivery.negative_plan import normalize_plan
from zhigou_toolchain.modeling.delivery.trace import public_value
from zhigou_toolchain.modeling.delivery.v3 import read_zip
from zhigou_toolchain.services.handoff import download
from zhigou_toolchain.services.modeling_sessions import read
from zhigou_toolchain.services.projects import get_project

ROOT = Path(__file__).parents[2]
_cases = {}
_snapshot = None


def plan_for(pack):
    return json.loads((ROOT / "tests/fixtures/handoff" / (pack + "-negative-plan.json")).read_bytes())


def build_stage_case(workspace, pack, *, snapshot_id=None):
    case = build_case(workspace, pack, negative_case_plan=plan_for(pack), record_trace=True,
                      configuration={"stage_source_snapshot": snapshot_id} if snapshot_id else None)
    service, project_id = case["service"], case["project_id"]
    session = read(get_project(service.root, project_id).root)
    checked = case["run"]("modeling.handoff.check", {"package_id": case["built"]["package_id"], "expected_revision": session["revision"]}, "negative-check")
    assert checked["status"] == "PASS", checked
    params = {**request_for(case), "negative_report_id": checked["report_id"]}
    exported = case["run"]("modeling.handoff.export", params, "stage-export")
    export_job = next(j for j in service.jobs.list_project(project_id) if j.operation_id == "modeling.handoff.export")
    raw = download(service, case["principal"], project_id, export_job.job_id)
    files = read_zip(raw)
    bound = json.loads(files["dependencies/run_bindings.json"])
    source_job = next(r["job_id"] for r in bound["agent_runs"] if r["operation_id"] == "compile.build")
    diagnostic = case["run"]("modeling.evolution.export", {"job_id": source_job, "batch_id": "stage-local", "profile": "local",
        "target_package_id": case["built"]["package_id"], "expected_revision": session["revision"]}, "stage-diagnostic")
    diagnostic_job = next(j for j in service.jobs.list_project(project_id) if (j.result or {}).get("sha256") == diagnostic["sha256"])
    import zipfile
    from io import BytesIO
    with zipfile.ZipFile(BytesIO(download(service, case["principal"], project_id, diagnostic_job.job_id))) as archive:
        diagnostic_files = {n: archive.read(n) for n in archive.namelist()}
    return {**case, "files": files, "raw": raw, "export_job": export_job, "receipt": exported,
            "negative_receipt": checked, "diagnostic": diagnostic_files, "session": session}


@pytest.fixture(scope="module", params=["hr", "forestry-workorders"])
def stage_case(request, tmp_path_factory):
    return cached_case(request.param, tmp_path_factory)


def cached_case(pack, tmp_path_factory):
    global _snapshot
    if pack in _cases:
        return _cases[pack]
    if _snapshot is None:
        from zhigou_toolchain.modeling.delivery.snapshot import source_snapshot
        _snapshot = json.loads(Path(os.environ["ZHIGOU_STAGE_SNAPSHOT_FILE"]).read_bytes()) if os.environ.get("ZHIGOU_STAGE_SNAPSHOT_FILE") else source_snapshot(ROOT)
    workspace = tmp_path_factory.mktemp("upgrade-hr" if pack == "hr" else "upgrade-forest")
    case = build_stage_case(workspace, pack, snapshot_id=_snapshot["snapshot_id"])
    case["source_snapshot"] = _snapshot
    if os.environ.get("ZHIGOU_STAGE_EVIDENCE_ROOT"):
        from tests.upgrade.stage_support import retain_stage_case
        retain_stage_case(case, Path(os.environ["ZHIGOU_STAGE_EVIDENCE_ROOT"]) / ("hr" if pack == "hr" else "forestry"))
    _cases[pack] = case
    return case


@pytest.fixture(scope="module")
def stage_archive_files(tmp_path_factory):
    from zhigou_toolchain.modeling.delivery.stage import compose_stage
    cases = {"hr": cached_case("hr", tmp_path_factory), "forestry": cached_case("forestry-workorders", tmp_path_factory)}
    snapshot = cases["hr"]["source_snapshot"]
    # Explicitly synthetic reader-contract receipts. Actual final receipts are
    # generated by verify_stage_handoff.py, never by this unit fixture.
    names = ("focused", "new-stage", "ruff", "types", "ontology", "services", "frontend-lint", "frontend-types", "frontend-tests", "frontend-build", "browser")
    evidence = {"relevant-test-receipts/fixture.log": b"SYNTHETIC_READER_FIXTURE_NOT_ACTUAL_REGRESSION\n"}
    stage = {"snapshot_id": snapshot["snapshot_id"], "source_before": snapshot["snapshot_id"], "source_after": snapshot["snapshot_id"],
        "source_unchanged": True, "module_acceptance": "PASS", "full_repository_status": "FAIL",
        "checks": [{"name": n, "exit_code": 0, "log": "fixture.log", "log_sha256": digest(evidence["relevant-test-receipts/fixture.log"])} for n in names]}
    evidence.update({"source-snapshot.json": json_bytes(snapshot), "stage-verification.json": json_bytes(stage),
        "full-regression-summary.json": json_bytes({"source_unchanged": True, "collection": {"complete": True}, "raw_status": "FAIL", "new_regressions_status": "NO_NEW_FAILURES"})})
    parts = {n: {"ontology-handoff.zip": c["raw"], "verification.json": json_bytes({"export_receipt": c["receipt"]}),
                 **{"diagnostics/" + k: v for k, v in c["diagnostic"].items()}} for n, c in cases.items()}
    return compose_stage(parts, evidence, snapshot["snapshot_id"], b"Synthetic reader contract fixture, not a released artifact.\n")


def test_final_zip_is_reopened_and_external_hash_is_independent(stage_archive_files, tmp_path):
    from zhigou_toolchain.modeling.delivery.stage import (
        export_stage,
        verify_stage_archive,
    )
    path = tmp_path / "stage.zip"
    result = export_stage(path, stage_archive_files)
    assert result["status"] == "VERIFIED" and result["module_acceptance"] == "PASS"
    assert verify_stage_archive(path)["module_acceptance"] == "UNATTESTED"
    with pytest.raises(ValueError, match="TRUSTED_STAGE_ARCHIVE"):
        verify_stage_archive(path, expected_sha256="0" * 64)


def test_context_tampering_rehashed_outer_manifest_still_rejected(stage_archive_files):
    from zhigou_toolchain.modeling.delivery.exchange_io import file_rows
    from zhigou_toolchain.modeling.delivery.stage import verify_stage_files
    altered = dict(stage_archive_files)
    name = "hr/diagnostics/local-trace.json"
    trace = json.loads(altered[name])
    trace["bindings"]["delivery_target"]["native_archive_sha256"] = "0" * 64
    altered[name] = json_bytes(trace)
    manifest = json.loads(altered["stage_manifest.json"])
    sizes = {r["path"]: r for r in file_rows({n: v for n, v in altered.items() if n != "stage_manifest.json"})}
    for row in manifest["files"]:
        row.update(sizes[row["path"]])
    altered["stage_manifest.json"] = json_bytes(manifest)
    with pytest.raises(ValueError, match="DELIVERY_TARGET_MISMATCH"):
        verify_stage_files(altered)


def native_files(raw):
    import zipfile
    from io import BytesIO
    with zipfile.ZipFile(BytesIO(raw)) as archive:
        return {n: archive.read(n) for n in archive.namelist()}


def recompose(files, bindings):
    deps = {n.removeprefix("dependencies/"): raw for n, raw in files.items() if n.startswith("dependencies/") and n != "dependencies/run_bindings.json"}
    return handoff_files(files["native/ontology.kgop"], native_files(files["native/ontology.kgop"]), bindings, deps)


def test_actual_negative_results_are_bound_and_categorized(stage_case):
    files = stage_case["files"]
    verified = verify_handoff(files, trusted_receipt=stage_case["receipt"])
    assert verified["format"] == "zhigou-ontology-handoff/1.1.0"
    assert verified["stage_acceptance"] == "PASS"
    payload = json.loads(files["tests/negative_cases.json"])
    assert payload["status"] == "PASS" and len(payload["report"]["cases"]) == 14
    assert {c["category"] for c in payload["report"]["cases"]} == {"SHACL", "PROVENANCE", "FILE_INTEGRITY", "STATE_GATE", "AUTHORIZATION", "DELIVERY_BINDING"}
    for row in payload["report"]["cases"]:
        assert row["status"] == "PASS" and row["observed"]["status"] == "DETECTED"
        assert row["tested_native_archive_sha256"] == digest(files["native/ontology.kgop"])
        assert digest(files["dependencies/" + row["input_artifact"]]) == row["mutated_input_sha256"]
    assert json.loads(files["mapping.json"])["native_execution_policy"] == "DECLARATIVE_NOT_EXECUTED"
    from zhigou_toolchain.modeling.control_plane.service import ModelingWorkspaceService
    workspace = ModelingWorkspaceService(get_project(stage_case["service"].root, stage_case["project_id"]).root)
    requests = (workspace.proposal_directory(stage_case["proposed"]["proposal"]["proposal_id"]) / "provider-requests.json").read_text(encoding="utf-8")
    assert "negative_case_plan" not in requests and payload["plan"]["plan_id"] not in requests


def test_immutable_ancestry_accepts_earlier_revision_and_rejects_tampering(stage_case):
    files, diagnostic = stage_case["files"], stage_case["diagnostic"]
    cover = compose(downstream=files, diagnostic=diagnostic)
    assert verify_cover(cover)["status"] == "VERIFIED"
    assert json.loads(cover["handoff_manifest.json"])["outputs"]["evolution"]["status"] == "BLOCKED"
    trace = json.loads(diagnostic["local-trace.json"])
    relation = associate_trace(trace, files)
    assert relation["relationship"] == "CURRENT_NATIVE_DEPENDENCY_ANCESTOR"
    b = json.loads(files["dependencies/run_bindings.json"])
    early = next(o for o in b["agent_runs"] if o["operation_id"] == "modeling.scope")
    assert early["session_revision"] < b["session_revision"]
    verify_ancestor(early, b["session_snapshot"])
    for key in ("package_id", "native_archive_sha256", "input_run_id", "session_revision", "compilation_plan_id"):
        changed = deepcopy(trace)
        changed["bindings"]["delivery_target"][key] = "WRONG"
        with pytest.raises(ValueError, match="DELIVERY_TARGET_MISMATCH"):
            associate_trace(changed, files)
    changed = deepcopy(trace)
    changed["bindings"]["job_id"] = "unrelated-job-in-same-session"
    with pytest.raises(ValueError, match="RUN_REFERENCE"):
        associate_trace(changed, files)
    changed = deepcopy(trace)
    changed["harness_manifest"]["resources"]["rules"] = {"altered": True}
    with pytest.raises(ValueError, match="HARNESS_START"):
        validate_trace_context(changed)


def test_rehashed_manifest_does_not_authorize_swapped_plan_or_results(stage_case):
    files = stage_case["files"]
    b = json.loads(files["dependencies/run_bindings.json"])
    b["negative_case_results"]["target"]["native_archive_sha256"] = "0" * 64
    tampered = recompose(files, b)
    with pytest.raises(ValueError, match="TARGET_MISMATCH"):
        verify_handoff(tampered)
    b = json.loads(files["dependencies/run_bindings.json"])
    b["negative_case_plan"]["version"] = "changed-after-freeze"
    with pytest.raises(ValueError, match="FREEZE|ORIGIN|PLAN"):
        verify_handoff(recompose(files, b))
    # Even an internally self-consistent attacker cannot replace the out-of-band
    # authorized service export receipt by rehashing the package's own manifest.
    b = json.loads(files["dependencies/run_bindings.json"])
    b["recipient"] = "another-recipient"
    tampered = recompose(files, b)
    with pytest.raises(ValueError, match="TRUSTED_EXPORT"):
        verify_handoff(tampered, trusted_receipt=stage_case["receipt"])


def test_no_plan_and_missing_rule_never_become_pass(stage_case, tmp_path, monkeypatch):
    files = stage_case["files"]
    native = native_files(files["native/ontology.kgop"])
    plan = deepcopy(json.loads(files["tests/negative_cases.json"])["plan"])
    plan["cases"] = plan["cases"][:1]
    plan["cases"][0]["rule_basis"]["shape_iri"] = "urn:not-a-domain-rule"
    result, _ = execute_negative_plan(plan, files, native, output=tmp_path / "not-applicable")
    assert result["status"] == "INCOMPLETE" and result["cases"][0]["status"] == "NOT_APPLICABLE"
    plan["cases"][0]["rule_basis"]["shape_iri"] = json.loads(files["tests/negative_cases.json"])["plan"]["cases"][0]["rule_basis"]["shape_iri"]
    monkeypatch.setattr("zhigou_toolchain.modeling.delivery.negative.shacl_check", lambda _: {"status": "TIMEOUT"})
    result, _ = execute_negative_plan(plan, files, native, output=tmp_path / "timeout")
    assert result["status"] == "FAIL" and result["cases"][0]["status"] != "PASS"


def test_plan_cannot_weaken_expected_rejection_and_is_excluded_from_content_logs():
    plan = plan_for("hr")
    assert normalize_plan(plan)["cases"]
    plan["cases"][0]["expected"]["code"] = "always-accept"
    with pytest.raises(ValueError):
        normalize_plan(plan)
    changes = set()
    safe = public_value({"negative_case_plan": plan}, changes)
    assert safe["negative_case_plan"] == "[REDACTED]" and changes


def test_stage_one_ancestor_does_not_require_later_tool_configuration():
    from zhigou_toolchain.contracts.canonical import semantic_hash
    frozen = {"run_id": "r", "configuration": {"model": "old"}}
    output = {"job_id": "j", "status": "CURRENT", "operation": "modeling.scope", "stage": 1, "dependency_digest": semantic_hash(frozen)}
    observation = {"job_id": "j", "operation_id": "modeling.scope", "session_id": "s", "session_revision": 1,
                   "session_output": output, "frozen_dependency_sha256": semantic_hash(frozen), "dependency_parts": dependency_parts(frozen)}
    session = {"session_id": "s", "revision": 9, "outputs": [output], "frozen": {**frozen, "configuration": {"model": "new"}}}
    verify_ancestor(observation, session)
    session["outputs"][0]["status"] = "STALE"
    with pytest.raises(ValueError, match="ANCESTOR_NOT_CURRENT"):
        verify_ancestor(observation, session)
