"""Part 2 of Stage 03 term catalog."""

from __future__ import annotations

from stage03_term import T, Term

TERMS_PART2: list[Term] = [
    # ---- SERVICE_CONTRACT ----
    T(local="TelecomService", term_type="Class", module="SERVICE_CONTRACT",
      label_en="Telecom Service", label_zh="电信服务",
      definition_en="A catalogued telecom service or product offering.",
      definition_zh="目录化的电信服务或产品。",
      source_status="INDUSTRY_ALIGNED", audit_decision="MOVE_MODULE"),
    T(local="ServiceSubscription", term_type="Class", module="SERVICE_CONTRACT",
      label_en="Service Subscription", label_zh="服务订阅",
      definition_en="An instantiated subscription linking a subscriber to a telecom service and billing account.",
      definition_zh="将用户关联到电信服务与计费账户的订阅实例。",
      source_status="INDUSTRY_ALIGNED", audit_decision="MOVE_MODULE"),
    T(local="ServiceContract", term_type="Class", module="SERVICE_CONTRACT",
      label_en="Service Contract", label_zh="服务合约",
      definition_en="A contractual commitment that may restrict portability until end time.",
      definition_zh="可能在截止前限制携转的服务合约。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="MobilePlan", term_type="Class", module="SERVICE_CONTRACT",
      label_en="Mobile Plan", label_zh="移动套餐",
      definition_en="A mobile telephony plan offering.",
      definition_zh="移动电话套餐。",
      superclass="TelecomService", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="BroadbandService", term_type="Class", module="SERVICE_CONTRACT",
      label_en="Broadband Service", label_zh="宽带服务",
      definition_en="A broadband access service offering.",
      definition_zh="宽带接入服务。",
      superclass="TelecomService", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="ValueAddedService", term_type="Class", module="SERVICE_CONTRACT",
      label_en="Value-Added Service", label_zh="增值业务",
      definition_en="A value-added telecom service.",
      definition_zh="电信增值业务。",
      superclass="TelecomService", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="SupplementaryCardService", term_type="Class", module="SERVICE_CONTRACT",
      label_en="Supplementary Card Service", label_zh="副卡业务",
      definition_en="A supplementary SIM card service.",
      definition_zh="副卡服务。",
      superclass="TelecomService", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="ConvergedService", term_type="Class", module="SERVICE_CONTRACT",
      label_en="Converged Service", label_zh="融合业务",
      definition_en="A converged multi-product service bundle.",
      definition_zh="融合多产品服务包。",
      superclass="TelecomService", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="CommitmentPeriod", term_type="Class", module="SERVICE_CONTRACT",
      label_en="Commitment Period", label_zh="承诺期",
      definition_en="A contractual commitment period attached to a service contract.",
      definition_zh="附属于服务合约的承诺期。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="TerminationAgreement", term_type="Class", module="SERVICE_CONTRACT",
      label_en="Termination Agreement", label_zh="解除协议",
      definition_en="An agreement to terminate a service contract.",
      definition_zh="终止服务合约的解除协议。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="subscribesToService", term_type="ObjectProperty", module="SERVICE_CONTRACT",
      label_en="subscribes to service", label_zh="订阅服务",
      definition_en="Links a service subscription to the subscribed telecom service.",
      definition_zh="将服务订阅关联到所订阅的电信服务。",
      domain="ServiceSubscription", range="TelecomService",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="billedThrough", term_type="ObjectProperty", module="SERVICE_CONTRACT",
      label_en="billed through", label_zh="经账户计费",
      definition_en="Links a service subscription to the telecom account used for billing.",
      definition_zh="将服务订阅关联到用于计费的电信账户。",
      domain="ServiceSubscription", range="TelecomAccount",
      source_status="LOCAL_EXTENSION", audit_decision="MODIFY",
      audit_notes="ODR-001: domain changed from Subscriber to ServiceSubscription."),
    T(local="governedByContract", term_type="ObjectProperty", module="SERVICE_CONTRACT",
      label_en="governed by contract", label_zh="受合约约束",
      definition_en="Links a service subscription to its governing service contract.",
      definition_zh="将服务订阅关联到约束它的服务合约。",
      domain="ServiceSubscription", range="ServiceContract",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="hasCommitmentPeriod", term_type="ObjectProperty", module="SERVICE_CONTRACT",
      label_en="has commitment period", label_zh="有承诺期",
      definition_en="Links a service contract to a commitment period.",
      definition_zh="将服务合约关联到承诺期。",
      domain="ServiceContract", range="CommitmentPeriod",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="hasTerminationAgreement", term_type="ObjectProperty", module="SERVICE_CONTRACT",
      label_en="has termination agreement", label_zh="有解除协议",
      definition_en="Links a service contract to a termination agreement.",
      definition_zh="将服务合约关联到解除协议。",
      domain="ServiceContract", range="TerminationAgreement",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="coversService", term_type="ObjectProperty", module="SERVICE_CONTRACT",
      label_en="covers service", label_zh="覆盖服务",
      definition_en="Links a contract or commitment to a covered telecom service.",
      definition_zh="将合约或承诺期关联到覆盖的电信服务。",
      domain="ServiceContract", range="TelecomService",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="subscriptionStatusCode", term_type="DatatypeProperty", module="SERVICE_CONTRACT",
      label_en="subscription status code", label_zh="订阅状态码",
      definition_en="Status code of a service subscription.",
      definition_zh="服务订阅状态代码。",
      domain="ServiceSubscription", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="contractStatusCode", term_type="DatatypeProperty", module="SERVICE_CONTRACT",
      label_en="contract status code", label_zh="合约状态码",
      definition_en="Status code of a service contract or contract-status evidence observation. No single OWL domain (used on contracts and evidence); constrained by SHACL profiles.",
      definition_zh="服务合约或合约状态证据观测的状态码。无单一 OWL Domain（合约与证据共用）；由 SHACL 配置约束。",
      range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MODIFY",
      audit_notes="Domain removed to avoid typing EvidenceRecord as ServiceContract."),
    T(local="contractEndTime", term_type="DatatypeProperty", module="SERVICE_CONTRACT",
      label_en="contract end time", label_zh="合约截止时间",
      definition_en="End datetime of a service contract or contract-status evidence observation. No single OWL domain; constrained by SHACL profiles.",
      definition_zh="服务合约或合约状态证据的截止时间。无单一 OWL Domain；由 SHACL 配置约束。",
      range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="MODIFY",
      audit_notes="Domain removed to avoid typing EvidenceRecord as ServiceContract."),
    T(local="commitmentStartTime", term_type="DatatypeProperty", module="SERVICE_CONTRACT",
      label_en="commitment start time", label_zh="承诺期开始",
      definition_en="Start datetime of a commitment period.",
      definition_zh="承诺期开始时间。",
      domain="CommitmentPeriod", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="commitmentEndTime", term_type="DatatypeProperty", module="SERVICE_CONTRACT",
      label_en="commitment end time", label_zh="承诺期结束",
      definition_en="End datetime of a commitment period.",
      definition_zh="承诺期结束时间。",
      domain="CommitmentPeriod", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="terminationSignedAt", term_type="DatatypeProperty", module="SERVICE_CONTRACT",
      label_en="termination signed at", label_zh="解除协议签署时间",
      definition_en="Datetime when a termination agreement was signed.",
      definition_zh="解除协议签署时间。",
      domain="TerminationAgreement", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="terminationEffectiveAt", term_type="DatatypeProperty", module="SERVICE_CONTRACT",
      label_en="termination effective at", label_zh="解除协议生效时间",
      definition_en="Datetime when a termination agreement becomes effective.",
      definition_zh="解除协议生效时间。",
      domain="TerminationAgreement", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="terminationStatusCode", term_type="DatatypeProperty", module="SERVICE_CONTRACT",
      label_en="termination status code", label_zh="解除协议状态码",
      definition_en="Status code of a termination agreement.",
      definition_zh="解除协议状态代码。",
      domain="TerminationAgreement", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),

    # ---- PROCESS ----
    T(local="MNPCase", term_type="Class", module="PROCESS",
      label_en="MNP Case", label_zh="携转案件",
      definition_en="A mobile number portability request case.",
      definition_zh="携号转网申请案件。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="MNPRequest", term_type="Class", module="PROCESS",
      label_en="MNP Request", label_zh="携转申请",
      definition_en="An MNP request specialization of an MNP case.",
      definition_zh="作为携转案件特例的携转申请。",
      superclass="MNPCase", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="ProcessStep", term_type="Class", module="PROCESS",
      label_en="Process Step", label_zh="流程步骤",
      definition_en="A discrete step in the MNP process lifecycle.",
      definition_zh="携转流程生命周期中的离散步骤。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="EligibilityCheck", term_type="Class", module="PROCESS",
      label_en="Eligibility Check", label_zh="资格检查步骤",
      definition_en="Process step for eligibility checking.",
      definition_zh="资格检查流程步骤。",
      superclass="ProcessStep", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="AuthorizationCodeRequest", term_type="Class", module="PROCESS",
      label_en="Authorization Code Request", label_zh="授权码申请",
      definition_en="Process step for requesting an authorization code.",
      definition_zh="申请授权码的流程步骤。",
      superclass="ProcessStep", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="AuthorizationCode", term_type="Class", module="PROCESS",
      label_en="Authorization Code", label_zh="授权码",
      definition_en="A time-bounded authorization code for port-in submission.",
      definition_zh="用于携入提交的有时限授权码。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="PortInSubmission", term_type="Class", module="PROCESS",
      label_en="Port-In Submission", label_zh="携入提交",
      definition_en="Process step for port-in submission.",
      definition_zh="携入提交流程步骤。",
      superclass="ProcessStep", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="PortingExecution", term_type="Class", module="PROCESS",
      label_en="Porting Execution", label_zh="携转执行",
      definition_en="Process step for porting execution.",
      definition_zh="携转执行流程步骤。",
      superclass="ProcessStep", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="PortingConfirmation", term_type="Class", module="PROCESS",
      label_en="Porting Confirmation", label_zh="携转确认",
      definition_en="Process step for porting confirmation.",
      definition_zh="携转确认流程步骤。",
      superclass="ProcessStep", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="ProcessEvent", term_type="Class", module="PROCESS",
      label_en="Process Event", label_zh="流程事件",
      definition_en="An event recorded during process execution.",
      definition_zh="流程执行期间记录的事件。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="MNPCaseStatus", term_type="Class", module="PROCESS",
      label_en="MNP Case Status", label_zh="案件流程状态",
      definition_en="Lifecycle status of an MNP case.",
      definition_zh="携转案件生命周期状态。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="concernsNumber", term_type="ObjectProperty", module="PROCESS",
      label_en="concerns number", label_zh="涉及号码",
      definition_en="Links an MNP case to the phone number concerned.",
      definition_zh="将携转案件关联到所涉号码。",
      domain="MNPCase", range="PhoneNumber",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="requestedBy", term_type="ObjectProperty", module="PROCESS",
      label_en="requested by", label_zh="由...申请",
      definition_en="Links an MNP case to the requesting subscriber.",
      definition_zh="将携转案件关联到申请人。",
      domain="MNPCase", range="Subscriber",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="hasEligibilityAssessment", term_type="ObjectProperty", module="PROCESS",
      label_en="has eligibility assessment", label_zh="有资格评估",
      definition_en="Links an MNP case to an eligibility assessment.",
      definition_zh="将携转案件关联到资格评估。",
      domain="MNPCase", range="EligibilityAssessment",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="hasCaseEvidence", term_type="ObjectProperty", module="PROCESS",
      label_en="has case evidence", label_zh="有案件证据",
      definition_en="Links an MNP case to evidence records available for evaluating that case.",
      definition_zh="将携转案件关联到可用于评估该案件的证据记录。",
      domain="MNPCase", range="EvidenceRecord", inverse="evidenceForCase",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE",
      audit_notes="ODR-003: availability, not assessment use."),
    T(local="hasProcessStep", term_type="ObjectProperty", module="PROCESS",
      label_en="has process step", label_zh="有流程步骤",
      definition_en="Links an MNP case to a process step.",
      definition_zh="将携转案件关联到流程步骤。",
      domain="MNPCase", range="ProcessStep",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="currentProcessStep", term_type="ObjectProperty", module="PROCESS",
      label_en="current process step", label_zh="当前流程步骤",
      definition_en="Links an MNP case to its current process step.",
      definition_zh="将携转案件关联到当前流程步骤。",
      domain="MNPCase", range="ProcessStep",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="nextProcessStep", term_type="ObjectProperty", module="PROCESS",
      label_en="next process step", label_zh="下一流程步骤",
      definition_en="Links a process step to its successor step.",
      definition_zh="将流程步骤关联到后续步骤。",
      domain="ProcessStep", range="ProcessStep",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="hasAuthorizationCode", term_type="ObjectProperty", module="PROCESS",
      label_en="has authorization code", label_zh="有授权码",
      definition_en="Links an MNP case to an authorization code.",
      definition_zh="将携转案件关联到授权码。",
      domain="MNPCase", range="AuthorizationCode",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="hasProcessEvent", term_type="ObjectProperty", module="PROCESS",
      label_en="has process event", label_zh="有流程事件",
      definition_en="Links an MNP case to a process event.",
      definition_zh="将携转案件关联到流程事件。",
      domain="MNPCase", range="ProcessEvent",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="hasCaseStatus", term_type="ObjectProperty", module="PROCESS",
      label_en="has case status", label_zh="有案件状态",
      definition_en="Links an MNP case to a case status.",
      definition_zh="将携转案件关联到案件状态。",
      domain="MNPCase", range="MNPCaseStatus",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="caseIdentifier", term_type="DatatypeProperty", module="PROCESS",
      label_en="case identifier", label_zh="案件编号",
      definition_en="Business identifier of an MNP case.",
      definition_zh="携转案件业务编号。",
      domain="MNPCase", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="stepCode", term_type="DatatypeProperty", module="PROCESS",
      label_en="step code", label_zh="步骤代码",
      definition_en="Code identifying a process step.",
      definition_zh="流程步骤识别代码。",
      domain="ProcessStep", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="authCodeValueMasked", term_type="DatatypeProperty", module="PROCESS",
      label_en="masked authorization code", label_zh="掩码授权码",
      definition_en="Masked authorization code value.",
      definition_zh="经过掩码的授权码值。",
      domain="AuthorizationCode", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="authCodeStatus", term_type="DatatypeProperty", module="PROCESS",
      label_en="authorization code status", label_zh="授权码状态",
      definition_en="Status code of an authorization code.",
      definition_zh="授权码状态代码。",
      domain="AuthorizationCode", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="authCodeIssuedAt", term_type="DatatypeProperty", module="PROCESS",
      label_en="authorization code issued at", label_zh="授权码签发时间",
      definition_en="Issuance datetime of an authorization code.",
      definition_zh="授权码签发时间。",
      domain="AuthorizationCode", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="authCodeValidUntil", term_type="DatatypeProperty", module="PROCESS",
      label_en="authorization code valid until", label_zh="授权码有效期至",
      definition_en="Validity end datetime of an authorization code.",
      definition_zh="授权码有效截止时间。",
      domain="AuthorizationCode", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="eventTypeCode", term_type="DatatypeProperty", module="PROCESS",
      label_en="event type code", label_zh="事件类型码",
      definition_en="Type code of a process event.",
      definition_zh="流程事件类型代码。",
      domain="ProcessEvent", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="eventTime", term_type="DatatypeProperty", module="PROCESS",
      label_en="event time", label_zh="事件时间",
      definition_en="Datetime of a process event.",
      definition_zh="流程事件发生时间。",
      domain="ProcessEvent", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="caseStatusCode", term_type="DatatypeProperty", module="PROCESS",
      label_en="case status code", label_zh="案件状态码",
      definition_en="Status code of an MNP case status resource.",
      definition_zh="携转案件状态资源的状态代码。",
      domain="MNPCaseStatus", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
]
