"""Part 3: compliance, evidence, provenance, code-list terms."""

from __future__ import annotations

from stage03_term import T, Term

TERMS_PART3: list[Term] = [
    # ---- EVIDENCE_TIME ----
    T(local="EvidenceRecord", term_type="Class", module="EVIDENCE_TIME",
      label_en="Evidence Record", label_zh="证据记录",
      definition_en="A dated business observation used as evidence in eligibility assessment.",
      definition_zh="用于资格评估的带时间戳业务观测证据。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="SystemObservation", term_type="Class", module="EVIDENCE_TIME",
      label_en="System Observation", label_zh="系统观测",
      definition_en="Evidence produced by an information system observation.",
      definition_zh="由信息系统观测产生的证据。",
      superclass="EvidenceRecord", source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="InformationSystem", term_type="Class", module="EVIDENCE_TIME",
      label_en="Information System", label_zh="信息系统",
      definition_en="A source system that generates evidence observations.",
      definition_zh="产生证据观测的来源系统。",
      source_status="INDUSTRY_ALIGNED", audit_decision="MOVE_MODULE"),
    T(local="APIResponse", term_type="Class", module="EVIDENCE_TIME",
      label_en="API Response", label_zh="接口响应证据",
      definition_en="Evidence captured from an API response payload.",
      definition_zh="从接口响应载荷捕获的证据。",
      superclass="SystemObservation", source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="EvidenceValidity", term_type="Class", module="EVIDENCE_TIME",
      label_en="Evidence Validity", label_zh="证据有效性",
      definition_en="A validity window annotation for an evidence record.",
      definition_zh="证据记录的有效期注解。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="ObservationTime", term_type="Class", module="EVIDENCE_TIME",
      label_en="Observation Time", label_zh="观测时间",
      definition_en="Time resource representing when an observation was made.",
      definition_zh="表示观测发生时间的时间资源。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="EvaluationTime", term_type="Class", module="EVIDENCE_TIME",
      label_en="Evaluation Time", label_zh="评估时间点",
      definition_en="Time resource representing an evaluation as-of instant.",
      definition_zh="表示评估基准时刻的时间资源。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="RecordedTime", term_type="Class", module="EVIDENCE_TIME",
      label_en="Recorded Time", label_zh="记录时间",
      definition_en="Time resource representing when a fact was recorded.",
      definition_zh="表示事实被记录时间的时间资源。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="evidenceForCase", term_type="ObjectProperty", module="EVIDENCE_TIME",
      label_en="evidence for case", label_zh="作为案件证据",
      definition_en="Inverse of hasCaseEvidence; links an evidence record to the case it belongs to.",
      definition_zh="hasCaseEvidence 的逆属性；将证据记录关联到所属案件。",
      domain="EvidenceRecord", range="MNPCase", inverse="hasCaseEvidence",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE",
      audit_notes="ODR-003: retained inverse."),
    T(local="hasSourceSystem", term_type="ObjectProperty", module="EVIDENCE_TIME",
      label_en="has source system", label_zh="有来源系统",
      definition_en="Links an evidence record to its producing information system.",
      definition_zh="将证据记录关联到产生它的信息系统。",
      domain="EvidenceRecord", range="InformationSystem",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="hasEvidenceValidity", term_type="ObjectProperty", module="EVIDENCE_TIME",
      label_en="has evidence validity", label_zh="有证据有效性",
      definition_en="Links an evidence record to a validity annotation.",
      definition_zh="将证据记录关联到有效性注解。",
      domain="EvidenceRecord", range="EvidenceValidity",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="observedAtTime", term_type="ObjectProperty", module="EVIDENCE_TIME",
      label_en="observed at time", label_zh="观测于",
      definition_en="Links an observation to an observation time resource.",
      definition_zh="将观测关联到观测时间资源。",
      domain="EvidenceRecord", range="ObservationTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="evaluatedAtTime", term_type="ObjectProperty", module="EVIDENCE_TIME",
      label_en="evaluated at time", label_zh="评估于",
      definition_en="Links an assessment-related resource to an evaluation time.",
      definition_zh="将评估相关资源关联到评估时间。",
      domain="EligibilityAssessment", range="EvaluationTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="recordedAtTime", term_type="ObjectProperty", module="EVIDENCE_TIME",
      label_en="recorded at time", label_zh="记录于",
      definition_en="Links a record to a recorded-time resource.",
      definition_zh="将记录关联到记录时间资源。",
      domain="EvidenceRecord", range="RecordedTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="observedAmount", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="observed amount", label_zh="观测金额",
      definition_en="Observed monetary amount on an evidence record.",
      definition_zh="证据记录上的观测金额。",
      domain="EvidenceRecord", range="xsd:decimal",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="currencyCode", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="currency code", label_zh="币种代码",
      definition_en="ISO-like currency code for an observed amount.",
      definition_zh="观测金额的币种代码。",
      domain="EvidenceRecord", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="evidenceGeneratedAt", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="evidence generated at", label_zh="证据生成时间",
      definition_en="Datetime when evidence was generated.",
      definition_zh="证据生成时间。",
      domain="EvidenceRecord", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="evidenceValidUntil", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="evidence valid until", label_zh="证据有效期至",
      definition_en="Datetime until which evidence remains valid.",
      definition_zh="证据有效截止时间。",
      domain="EvidenceRecord", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="evidenceStatus", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="evidence status", label_zh="证据状态",
      definition_en="Status code of an evidence record (VALID/EXPIRED/REVOKED/UNKNOWN).",
      definition_zh="证据记录状态码（VALID/EXPIRED/REVOKED/UNKNOWN）。",
      domain="EvidenceRecord", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="evidenceType", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="evidence type", label_zh="证据类型",
      definition_en="Type code classifying an evidence record.",
      definition_zh="证据记录类型代码。",
      domain="EvidenceRecord", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="identityMatchFlag", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="identity match flag", label_zh="身份匹配标志",
      definition_en="Boolean flag indicating identity match on evidence.",
      definition_zh="证据上的身份匹配布尔标志。",
      domain="EvidenceRecord", range="xsd:boolean",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="numberStatusCode", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="number status code", label_zh="号码状态码",
      definition_en="Number status observed on evidence.",
      definition_zh="证据中观测到的号码状态。",
      domain="EvidenceRecord", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="daysSinceLastPort", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="days since last port", label_zh="距上次携转天数",
      definition_en="Observed days since last portability event.",
      definition_zh="距上次携转事件的天数观测。",
      domain="EvidenceRecord", range="xsd:integer",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="hasPaymentArrangement", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="has payment arrangement", label_zh="是否有缴费安排",
      definition_en="Boolean flag on evidence indicating a payment arrangement.",
      definition_zh="证据上表示是否存在缴费安排的布尔标志。",
      domain="EvidenceRecord", range="xsd:boolean",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="systemIdentifier", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="system identifier", label_zh="系统标识",
      definition_en="Business identifier of an information system.",
      definition_zh="信息系统业务标识。",
      domain="InformationSystem", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="timeInstant", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="time instant", label_zh="时间瞬间",
      definition_en="xsd:dateTime value carried by a time resource.",
      definition_zh="时间资源承载的 xsd:dateTime 值。",
      range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="validityStart", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="validity start", label_zh="有效期开始",
      definition_en="Start of an evidence validity window.",
      definition_zh="证据有效期开始。",
      domain="EvidenceValidity", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="validityEnd", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="validity end", label_zh="有效期结束",
      definition_en="End of an evidence validity window.",
      definition_zh="证据有效期结束。",
      domain="EvidenceValidity", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="apiEndpointCode", term_type="DatatypeProperty", module="EVIDENCE_TIME",
      label_en="API endpoint code", label_zh="接口端点代码",
      definition_en="Code identifying the API endpoint that produced evidence.",
      definition_zh="产生证据的接口端点代码。",
      domain="APIResponse", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),

    # ---- COMPLIANCE ----
    T(local="EligibilityAssessment", term_type="Class", module="COMPLIANCE",
      label_en="Eligibility Assessment", label_zh="资格评估",
      definition_en="A deterministic evaluation of an MNP case against eligibility rules and evidence.",
      definition_zh="依据资格规则与证据对携转案件进行的确定性评估。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="EligibilityDecision", term_type="Class", module="COMPLIANCE",
      label_en="Eligibility Decision", label_zh="资格决定",
      definition_en="Abstract decision outcome of an eligibility assessment.",
      definition_zh="资格评估的抽象决定结果。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="EligibleDecision", term_type="Class", module="COMPLIANCE",
      label_en="Eligible Decision", label_zh="可携决定",
      definition_en="Decision that the case is eligible for portability.",
      definition_zh="案件符合携转资格的决定。",
      superclass="EligibilityDecision",
      disjoint_with=["BlockingDecision", "ConditionalDecision", "ManualReviewDecision"],
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="BlockingDecision", term_type="Class", module="COMPLIANCE",
      label_en="Blocking Decision", label_zh="阻塞决定",
      definition_en="Decision that portability is blocked.",
      definition_zh="携转被阻塞的决定。",
      superclass="EligibilityDecision",
      disjoint_with=["EligibleDecision", "ConditionalDecision", "ManualReviewDecision"],
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="ConditionalDecision", term_type="Class", module="COMPLIANCE",
      label_en="Conditional Decision", label_zh="有条件决定",
      definition_en="Decision that portability is conditionally allowed.",
      definition_zh="有条件允许携转的决定。",
      superclass="EligibilityDecision",
      disjoint_with=["EligibleDecision", "BlockingDecision", "ManualReviewDecision"],
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="ManualReviewDecision", term_type="Class", module="COMPLIANCE",
      label_en="Manual Review Decision", label_zh="人工复核决定",
      definition_en="Decision that manual review is required.",
      definition_zh="需要人工复核的决定。",
      superclass="EligibilityDecision",
      disjoint_with=["EligibleDecision", "BlockingDecision", "ConditionalDecision"],
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="EligibilityRule", term_type="Class", module="COMPLIANCE",
      label_en="Eligibility Rule", label_zh="资格规则",
      definition_en="A versioned eligibility rule operationalizing regulatory clauses.",
      definition_zh="落实监管条款的版本化资格规则。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="BlockingReason", term_type="Class", module="COMPLIANCE",
      label_en="Blocking Reason", label_zh="阻塞原因",
      definition_en="An independent reason that contributes to a blocking or review outcome.",
      definition_zh="导致阻塞或复核结果的独立原因。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="RemediationAction", term_type="Class", module="COMPLIANCE",
      label_en="Remediation Action", label_zh="处理动作",
      definition_en="A recommended action a user or operator should take.",
      definition_zh="建议用户或运营人员采取的处理动作。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="RegulatoryClause", term_type="Class", module="COMPLIANCE",
      label_en="Regulatory Clause", label_zh="监管条款",
      definition_en="A specific clause within a regulatory document.",
      definition_zh="监管文件中的具体条款。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="RegulatoryDocument", term_type="Class", module="COMPLIANCE",
      label_en="Regulatory Document", label_zh="监管文件",
      definition_en="A regulatory or policy document containing clauses.",
      definition_zh="包含条款的监管或政策文件。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="RuleVersion", term_type="Class", module="COMPLIANCE",
      label_en="Rule Version", label_zh="规则版本",
      definition_en="A concrete version of an eligibility rule with effective dates.",
      definition_zh="带生效日期的资格规则具体版本。",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="ReassessmentMarker", term_type="Class", module="COMPLIANCE",
      label_en="Reassessment Marker", label_zh="重评标记",
      definition_en="Marker indicating an assessment requires reassessment after rule change.",
      definition_zh="表示规则变更后评估需重评的标记。",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="AssessmentDependency", term_type="Class", module="COMPLIANCE",
      label_en="Assessment Dependency (deprecated)", label_zh="评估依赖（已弃用）",
      definition_en="Deprecated wrapper formerly linking assessments to evidence/rule versions without independent metadata.",
      definition_zh="已弃用；原用于包装评估对证据/规则版本的依赖，无独立元数据。",
      deprecated=True, replacement="usesEvidence",
      source_status="LOCAL_EXTENSION", audit_decision="DEPRECATE",
      audit_notes="ODR-004."),
    T(local="usesEvidence", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="uses evidence", label_zh="使用证据",
      definition_en="Links an eligibility assessment to the evidence snapshot actually used in that assessment.",
      definition_zh="将资格评估关联到该次评估实际使用的证据快照。",
      domain="EligibilityAssessment", range="EvidenceRecord",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE",
      audit_notes="ODR-003/004."),
    T(local="evaluatedByRule", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="evaluated by rule", label_zh="由规则评估",
      definition_en="Links an assessment to an eligibility rule consulted.",
      definition_zh="将评估关联到所参照的资格规则。",
      domain="EligibilityAssessment", range="EligibilityRule",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="usesRuleVersion", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="uses rule version", label_zh="使用规则版本",
      definition_en="Links an assessment to the concrete rule version used.",
      definition_zh="将评估关联到实际使用的规则版本。",
      domain="EligibilityAssessment", range="RuleVersion",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="producesDecision", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="produces decision", label_zh="产生决定",
      definition_en="Links an eligibility assessment to its formal decision outcome.",
      definition_zh="将资格评估关联到正式决定结果。",
      domain="EligibilityAssessment", range="EligibilityDecision",
      characteristics="FunctionalProperty",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE",
      audit_notes="ODR-002."),
    T(local="hasBlockingReason", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="has blocking reason", label_zh="有阻塞原因",
      definition_en="Links an eligibility decision to a blocking reason that justifies it.",
      definition_zh="将资格决定关联到支撑该决定的阻塞原因。",
      domain="EligibilityDecision", range="BlockingReason",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT",
      audit_notes="ODR-002 replacement for producesBlockingReason."),
    T(local="producesBlockingReason", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="produces blocking reason (deprecated)", label_zh="产生阻塞原因（已弃用）",
      definition_en="Deprecated. Blocking reasons attach to decisions via hasBlockingReason.",
      definition_zh="已弃用。阻塞原因通过 hasBlockingReason 挂在决定上。",
      domain="EligibilityAssessment", range="BlockingReason", deprecated=True,
      replacement="hasBlockingReason",
      source_status="LOCAL_EXTENSION", audit_decision="DEPRECATE",
      audit_notes="ODR-002."),
    T(local="dependsOn", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="depends on (deprecated)", label_zh="依赖于（已弃用）",
      definition_en="Deprecated assessment-to-dependency wrapper property.",
      definition_zh="已弃用的评估依赖包装属性。",
      domain="EligibilityAssessment", range="AssessmentDependency", deprecated=True,
      replacement="usesEvidence",
      source_status="LOCAL_EXTENSION", audit_decision="DEPRECATE",
      audit_notes="ODR-004."),
    T(local="dependsOnRuleVersion", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="depends on rule version (deprecated)", label_zh="依赖规则版本（已弃用）",
      definition_en="Deprecated; use usesRuleVersion directly.",
      definition_zh="已弃用；请直接使用 usesRuleVersion。",
      domain="AssessmentDependency", range="RuleVersion", deprecated=True,
      replacement="usesRuleVersion",
      source_status="LOCAL_EXTENSION", audit_decision="DEPRECATE"),
    T(local="dependsOnEvidence", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="depends on evidence (deprecated)", label_zh="依赖证据（已弃用）",
      definition_en="Deprecated; use usesEvidence directly.",
      definition_zh="已弃用；请直接使用 usesEvidence。",
      domain="AssessmentDependency", range="EvidenceRecord", deprecated=True,
      replacement="usesEvidence",
      source_status="LOCAL_EXTENSION", audit_decision="DEPRECATE"),
    T(local="aboutCase", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="about case", label_zh="关于案件",
      definition_en="Links an assessment to the MNP case it evaluates.",
      definition_zh="将评估关联到其所评估的携转案件。",
      domain="EligibilityAssessment", range="MNPCase",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="recommendsAction", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="recommends action", label_zh="建议动作",
      definition_en="Links a blocking reason to a remediation action.",
      definition_zh="将阻塞原因关联到处理动作。",
      domain="BlockingReason", range="RemediationAction",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="operationalizesClause", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="operationalizes clause", label_zh="落实条款",
      definition_en="Links an eligibility rule to a regulatory clause it operationalizes.",
      definition_zh="将资格规则关联到其所落实的监管条款。",
      domain="EligibilityRule", range="RegulatoryClause",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="partOfDocument", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="part of document", label_zh="属于文件",
      definition_en="Links a regulatory clause to its parent document.",
      definition_zh="将监管条款关联到所属文件。",
      domain="RegulatoryClause", range="RegulatoryDocument",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="affectsAssessment", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="affects assessment", label_zh="影响评估",
      definition_en="Links a newer rule version to assessments affected by supersession.",
      definition_zh="将新规则版本关联到受其替代影响的评估。",
      domain="RuleVersion", range="EligibilityAssessment",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="hasRuleVersion", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="has rule version", label_zh="有规则版本",
      definition_en="Links an eligibility rule to a concrete rule version.",
      definition_zh="将资格规则关联到具体规则版本。",
      domain="EligibilityRule", range="RuleVersion",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="supportedByEvidence", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="supported by evidence", label_zh="由证据支持",
      definition_en="Links a blocking reason to supporting evidence.",
      definition_zh="将阻塞原因关联到支持证据。",
      domain="BlockingReason", range="EvidenceRecord",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="triggeredByRule", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="triggered by rule", label_zh="由规则触发",
      definition_en="Links a blocking reason to the triggering eligibility rule.",
      definition_zh="将阻塞原因关联到触发规则。",
      domain="BlockingReason", range="EligibilityRule",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="triggeredByRuleVersion", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="triggered by rule version", label_zh="由规则版本触发",
      definition_en="Links a blocking reason to the triggering rule version.",
      definition_zh="将阻塞原因关联到触发规则版本。",
      domain="BlockingReason", range="RuleVersion",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="citesClause", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="cites clause", label_zh="引用条款",
      definition_en="Links a blocking reason to a cited regulatory clause.",
      definition_zh="将阻塞原因关联到所引用的监管条款。",
      domain="BlockingReason", range="RegulatoryClause",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="supersedesRuleVersion", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="supersedes rule version", label_zh="替代规则版本",
      definition_en="Links a rule version to the prior version it supersedes.",
      definition_zh="将规则版本关联到其所替代的先前版本。",
      domain="RuleVersion", range="RuleVersion",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="markedForReassessment", term_type="ObjectProperty", module="COMPLIANCE",
      label_en="marked for reassessment", label_zh="标记需重评",
      definition_en="Links an assessment to a reassessment marker.",
      definition_zh="将评估关联到重评标记。",
      domain="EligibilityAssessment", range="ReassessmentMarker",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="assessmentIdentifier", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="assessment identifier", label_zh="评估编号",
      definition_en="Business identifier of an eligibility assessment.",
      definition_zh="资格评估业务编号。",
      domain="EligibilityAssessment", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="assessmentTime", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="assessment time", label_zh="评估时间",
      definition_en="As-of datetime used when selecting rule versions and evaluating evidence validity.",
      definition_zh="选择规则版本并评估证据有效性时使用的基准时间。",
      domain="EligibilityAssessment", range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="requiresReassessment", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="requires reassessment", label_zh="需要重评",
      definition_en="Boolean flag indicating reassessment is required.",
      definition_zh="表示需要重评的布尔标志。",
      domain="EligibilityAssessment", range="xsd:boolean",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="decisionCode", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="decision code", label_zh="决定代码",
      definition_en="Code of an eligibility decision outcome.",
      definition_zh="资格决定结果代码。",
      domain="EligibilityDecision", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="reasonCode", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="reason code", label_zh="原因代码",
      definition_en="Code identifying a blocking reason.",
      definition_zh="阻塞原因识别代码。",
      domain="BlockingReason", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="reasonDescription", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="reason description", label_zh="原因说明",
      definition_en="Human-readable description of a blocking reason.",
      definition_zh="阻塞原因的可读说明。",
      domain="BlockingReason", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="actionCode", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="action code", label_zh="动作代码",
      definition_en="Code identifying a remediation action.",
      definition_zh="处理动作识别代码。",
      domain="RemediationAction", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="actionDescription", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="action description", label_zh="动作说明",
      definition_en="Human-readable description of a remediation action.",
      definition_zh="处理动作的可读说明。",
      domain="RemediationAction", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="ruleIdentifier", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="rule identifier", label_zh="规则编号",
      definition_en="Business identifier of an eligibility rule.",
      definition_zh="资格规则业务编号。",
      domain="EligibilityRule", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="ruleVersion", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="rule version label", label_zh="规则版本标签",
      definition_en="Version label string for a rule or rule version.",
      definition_zh="规则或规则版本的版本标签字符串。",
      range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="effectiveFrom", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="effective from", label_zh="生效自",
      definition_en="Datetime from which a rule version is effective.",
      definition_zh="规则版本生效起始时间。",
      range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="effectiveTo", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="effective to", label_zh="生效至",
      definition_en="Datetime until which a rule version is effective.",
      definition_zh="规则版本生效截止时间。",
      range="xsd:dateTime",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="clauseIdentifier", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="clause identifier", label_zh="条款编号",
      definition_en="Business identifier of a regulatory clause.",
      definition_zh="监管条款业务编号。",
      domain="RegulatoryClause", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="clauseText", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="clause text", label_zh="条款文本",
      definition_en="Textual content of a regulatory clause.",
      definition_zh="监管条款文本内容。",
      domain="RegulatoryClause", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
    T(local="documentIdentifier", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="document identifier", label_zh="文件编号",
      definition_en="Business identifier of a regulatory document.",
      definition_zh="监管文件业务编号。",
      domain="RegulatoryDocument", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="MOVE_MODULE"),
    T(local="reassessmentReason", term_type="DatatypeProperty", module="COMPLIANCE",
      label_en="reassessment reason", label_zh="重评原因",
      definition_en="Reason text for a reassessment marker.",
      definition_zh="重评标记的原因文本。",
      domain="ReassessmentMarker", range="xsd:string",
      source_status="LOCAL_EXTENSION", audit_decision="ACCEPT"),
]
