"""Part 4: modeling provenance and code-list terms."""

from __future__ import annotations

from stage03_term import T, Term

TERMS_PART4: list[Term] = [
    # ---- MODELING_PROVENANCE ----
    T(local="MappingRecord", term_type="Class", module="MODELING_PROVENANCE",
      label_en="Mapping Record", label_zh="映射记录",
      definition_en="A documented mapping from an external API field to an MNP term.",
      definition_zh="从外部 API 字段到 MNP 术语的文档化映射。",
      source_status="PROJECT_GOVERNANCE", audit_decision="MOVE_MODULE",
      audit_notes="ODR-005: moved out of core."),
    T(local="ModelingAssertion", term_type="Class", module="MODELING_PROVENANCE",
      label_en="Modeling Assertion", label_zh="建模断言",
      definition_en="A proposed or confirmed assertion about ontology modeling, distinct from business case facts.",
      definition_zh="关于本体建模的提议或确认断言，区别于业务案件事实。",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT",
      audit_notes="ODR-005 TBox only."),
    T(local="RelationAssertion", term_type="Class", module="MODELING_PROVENANCE",
      label_en="Relation Assertion", label_zh="关系断言",
      definition_en="A modeling assertion that proposes a relation between terms or instances for review.",
      definition_zh="提议术语或实例间关系以供审核的建模断言。",
      superclass="ModelingAssertion",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="ModelingEvidence", term_type="Class", module="MODELING_PROVENANCE",
      label_en="Modeling Evidence", label_zh="建模证据",
      definition_en="Evidence supporting a modeling assertion; not a business EvidenceRecord.",
      definition_zh="支撑建模断言的证据；不是业务 EvidenceRecord。",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT",
      audit_notes="ODR-005: disjoint from business evidence conceptually."),
    T(local="SourceRecord", term_type="Class", module="MODELING_PROVENANCE",
      label_en="Source Record", label_zh="来源记录",
      definition_en="A source system or document record used as modeling input.",
      definition_zh="用作建模输入的来源系统或文件记录。",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="SourceField", term_type="Class", module="MODELING_PROVENANCE",
      label_en="Source Field", label_zh="来源字段",
      definition_en="A field within a source record used in a mapping.",
      definition_zh="映射所使用的来源记录中的字段。",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="MappingRule", term_type="Class", module="MODELING_PROVENANCE",
      label_en="Mapping Rule", label_zh="映射规则",
      definition_en="A reusable rule describing how source fields map to ontology terms.",
      definition_zh="描述来源字段如何映射到本体术语的可复用规则。",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="ReviewDecision", term_type="Class", module="MODELING_PROVENANCE",
      label_en="Review Decision", label_zh="建模审核决定",
      definition_en="A human review decision on a modeling assertion; not an EligibilityDecision.",
      definition_zh="对建模断言的人工审核决定；不是资格决定。",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT",
      audit_notes="ODR-005: must not be confused with eligibility decisions."),
    T(local="hasModelingEvidence", term_type="ObjectProperty", module="MODELING_PROVENANCE",
      label_en="has modeling evidence", label_zh="有建模证据",
      definition_en="Links a modeling assertion to modeling evidence.",
      definition_zh="将建模断言关联到建模证据。",
      domain="ModelingAssertion", range="ModelingEvidence",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="mapsSourceField", term_type="ObjectProperty", module="MODELING_PROVENANCE",
      label_en="maps source field", label_zh="映射来源字段",
      definition_en="Links a mapping record to a source field.",
      definition_zh="将映射记录关联到来源字段。",
      domain="MappingRecord", range="SourceField",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="usesMappingRule", term_type="ObjectProperty", module="MODELING_PROVENANCE",
      label_en="uses mapping rule", label_zh="使用映射规则",
      definition_en="Links a mapping record to a mapping rule.",
      definition_zh="将映射记录关联到映射规则。",
      domain="MappingRecord", range="MappingRule",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="hasReviewDecision", term_type="ObjectProperty", module="MODELING_PROVENANCE",
      label_en="has review decision", label_zh="有审核决定",
      definition_en="Links a modeling assertion to a review decision.",
      definition_zh="将建模断言关联到审核决定。",
      domain="ModelingAssertion", range="ReviewDecision",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="fieldOfSource", term_type="ObjectProperty", module="MODELING_PROVENANCE",
      label_en="field of source", label_zh="属于来源",
      definition_en="Links a source field to its parent source record.",
      definition_zh="将来源字段关联到所属来源记录。",
      domain="SourceField", range="SourceRecord",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="sourceApi", term_type="DatatypeProperty", module="MODELING_PROVENANCE",
      label_en="source API", label_zh="来源 API",
      definition_en="Identifier of the source API for a mapping record.",
      definition_zh="映射记录的来源 API 标识。",
      domain="MappingRecord", range="xsd:string",
      source_status="PROJECT_GOVERNANCE", audit_decision="MOVE_MODULE"),
    T(local="sourceFieldPath", term_type="DatatypeProperty", module="MODELING_PROVENANCE",
      label_en="source field path", label_zh="来源字段路径",
      definition_en="Path of the source field within an API payload.",
      definition_zh="API 载荷中来源字段的路径。",
      domain="MappingRecord", range="xsd:string",
      source_status="PROJECT_GOVERNANCE", audit_decision="MOVE_MODULE"),
    T(local="targetTerm", term_type="DatatypeProperty", module="MODELING_PROVENANCE",
      label_en="target term", label_zh="目标术语",
      definition_en="Local name or IRI string of the target ontology term.",
      definition_zh="目标本体术语的本地名或 IRI 字符串。",
      domain="MappingRecord", range="xsd:string",
      source_status="PROJECT_GOVERNANCE", audit_decision="MOVE_MODULE"),
    T(local="mappingReviewStatus", term_type="DatatypeProperty", module="MODELING_PROVENANCE",
      label_en="mapping review status", label_zh="映射审核状态",
      definition_en="Review status of a mapping record.",
      definition_zh="映射记录的审核状态。",
      domain="MappingRecord", range="xsd:string",
      source_status="PROJECT_GOVERNANCE", audit_decision="MOVE_MODULE"),
    T(local="reviewOutcomeCode", term_type="DatatypeProperty", module="MODELING_PROVENANCE",
      label_en="review outcome code", label_zh="审核结果代码",
      definition_en="Outcome code of a modeling review decision.",
      definition_zh="建模审核决定的结果代码。",
      domain="ReviewDecision", range="xsd:string",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),

    # ---- CODE_LIST ----
    T(local="CodeListEntry", term_type="Class", module="CODE_LIST",
      label_en="Code List Entry", label_zh="码表条目",
      definition_en="An entry in a controlled code list.",
      definition_zh="受控码表中的条目。",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="codeListName", term_type="DatatypeProperty", module="CODE_LIST",
      label_en="code list name", label_zh="码表名称",
      definition_en="Name of the controlled code list.",
      definition_zh="受控码表名称。",
      domain="CodeListEntry", range="xsd:string",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="codeValue", term_type="DatatypeProperty", module="CODE_LIST",
      label_en="code value", label_zh="代码值",
      definition_en="Canonical value of a code list entry.",
      definition_zh="码表条目的规范代码值。",
      domain="CodeListEntry", range="xsd:string",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="codeLabelEn", term_type="DatatypeProperty", module="CODE_LIST",
      label_en="code label (English)", label_zh="代码英文标签",
      definition_en="English label of a code list entry.",
      definition_zh="码表条目的英文标签。",
      domain="CodeListEntry", range="xsd:string",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="codeLabelZh", term_type="DatatypeProperty", module="CODE_LIST",
      label_en="code label (Chinese)", label_zh="代码中文标签",
      definition_en="Chinese label of a code list entry.",
      definition_zh="码表条目的中文标签。",
      domain="CodeListEntry", range="xsd:string",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="Code-Evidence-VALID", term_type="Individual", module="CODE_LIST",
      label_en="Evidence status VALID", label_zh="证据状态-有效",
      definition_en="Controlled code for valid evidence status.",
      definition_zh="证据有效状态的受控代码。",
      code_list_name="evidenceStatus", code_value="VALID",
      code_label_en="Valid", code_label_zh="有效",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="Code-Evidence-EXPIRED", term_type="Individual", module="CODE_LIST",
      label_en="Evidence status EXPIRED", label_zh="证据状态-过期",
      definition_en="Controlled code for expired evidence status.",
      definition_zh="证据过期状态的受控代码。",
      code_list_name="evidenceStatus", code_value="EXPIRED",
      code_label_en="Expired", code_label_zh="过期",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="Code-Auth-VALID", term_type="Individual", module="CODE_LIST",
      label_en="Auth code VALID", label_zh="授权码-有效",
      definition_en="Controlled code for valid authorization code status.",
      definition_zh="授权码有效状态的受控代码。",
      code_list_name="authCodeStatus", code_value="VALID",
      code_label_en="Valid", code_label_zh="有效",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="Code-Auth-EXPIRED", term_type="Individual", module="CODE_LIST",
      label_en="Auth code EXPIRED", label_zh="授权码-过期",
      definition_en="Controlled code for expired authorization code status.",
      definition_zh="授权码过期状态的受控代码。",
      code_list_name="authCodeStatus", code_value="EXPIRED",
      code_label_en="Expired", code_label_zh="已过期",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="Code-Auth-MISSING", term_type="Individual", module="CODE_LIST",
      label_en="Auth code MISSING", label_zh="授权码-缺失",
      definition_en="Controlled code for missing authorization code status.",
      definition_zh="授权码缺失状态的受控代码。",
      code_list_name="authCodeStatus", code_value="MISSING",
      code_label_en="Missing", code_label_zh="缺失",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="Code-Step-ELIGIBILITY_CHECK", term_type="Individual", module="CODE_LIST",
      label_en="Step ELIGIBILITY_CHECK", label_zh="步骤-资格检查",
      definition_en="Controlled code for eligibility check process step.",
      definition_zh="资格检查流程步骤受控代码。",
      code_list_name="processStep", code_value="ELIGIBILITY_CHECK",
      code_label_en="Eligibility Check", code_label_zh="资格检查",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="Code-Step-AUTHORIZATION_CODE_REQUEST", term_type="Individual", module="CODE_LIST",
      label_en="Step AUTHORIZATION_CODE_REQUEST", label_zh="步骤-授权码申请",
      definition_en="Controlled code for authorization code request step.",
      definition_zh="授权码申请流程步骤受控代码。",
      code_list_name="processStep", code_value="AUTHORIZATION_CODE_REQUEST",
      code_label_en="Authorization Code Request", code_label_zh="授权码申请",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
    T(local="Code-Step-PORT_IN_SUBMISSION", term_type="Individual", module="CODE_LIST",
      label_en="Step PORT_IN_SUBMISSION", label_zh="步骤-携入提交",
      definition_en="Controlled code for port-in submission process step.",
      definition_zh="携入提交流程步骤受控代码。",
      code_list_name="processStep", code_value="PORT_IN_SUBMISSION",
      code_label_en="Port-In Submission", code_label_zh="携入提交",
      source_status="PROJECT_GOVERNANCE", audit_decision="ACCEPT"),
]
