PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX mnp: <https://yangjunjie-lin.github.io/KG-MNP-Demo/ontology/terms#>
SELECT ?s ?p ?o WHERE { GRAPH <urn:kg-mnp:graph:abox:8ae53bb08ea73496efc34a7247fa94e9c9b46c016d90dd3d2e6cf04feac6392a> { ?s ?p ?o . FILTER(!(?p = rdf:type && ?o = owl:Ontology) && ?p != owl:imports) FILTER NOT EXISTS { GRAPH <urn:kg-mnp:graph:modeling-provenance:8ae53bb08ea73496efc34a7247fa94e9c9b46c016d90dd3d2e6cf04feac6392a> { ?assertion a owl:Axiom ; owl:annotatedSource ?s ; owl:annotatedProperty ?p ; owl:annotatedTarget ?o ; mnp:hasReviewDecision ?decision } } } } ORDER BY ?s ?p ?o
