"""Stable Project Workspace status values."""

UNINITIALIZED = "UNINITIALIZED"
VALID = "VALID"
INVALID = "INVALID"
STALE_PROJECT_LOCK = "STALE_PROJECT_LOCK"
STALE_DOMAIN_PACK_LOCK = "STALE_DOMAIN_PACK_LOCK"
MISSING_DOMAIN_PACK = "MISSING_DOMAIN_PACK"
CONTRACT_CATALOG_MISMATCH = "CONTRACT_CATALOG_MISMATCH"

ALL_STATUSES = (
    UNINITIALIZED,
    VALID,
    INVALID,
    STALE_PROJECT_LOCK,
    STALE_DOMAIN_PACK_LOCK,
    MISSING_DOMAIN_PACK,
    CONTRACT_CATALOG_MISMATCH,
)

